### ISSUE TITLE
Medikament auswählen muss immer ein normaler Links-Klick sein.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#103]
Wenn der User ein Medikament auswählt (Klick auf die Packung) muss es immer ein normaler Klick sein, kein Rechts-Klick. Zur Zeit ist es im Kompendiums-Modus ein Rechts-Klick und im Rezeptmodus ein Links-Klick. Das ist nicht gut.

**Comment by zdavatz** [comment]
Der Klick auf den Markennamen zeigt immer die Fachinfo. Der Klick auf die Packung zeigt fügt die Packung immer dem Rezept hinzu.

**Comment by grauwoelfchen** [comment]
@zdavatz OK.
