### ISSUE TITLE
Bind delete action for saved prescription file to Backspace

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#107]
Remove right click event and context menu.

**Comment by grauwoelfchen** [comment]
duplicated to #103

**Comment by grauwoelfchen** [comment]
@zdavatz Jetzt, Key down event von `Backspace` und `Löschen` auf ContextMenu via Recht-Klick beides gehen.

**Comment by zdavatz** [comment]
Sehr gut! Bravo!!!
