### ISSUE TITLE
Windows Certification Test still fails

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#11]
this needs to be fixed.
![app_cert_fails](https://user-images.githubusercontent.com/4953/40041139-4aa12cba-581d-11e8-99a0-1be1936843bc.png)

Steps to reproduce
1. Open VS
2. Right-Click on _AppX_Gen_AmiKo_ in _Solution_Explorer_
3. Store > App-Paket erstellen
4. Choose the first option in the list (create Package for Microsoft Store)
5. Select x86 and x64
6. Erstellen
7. Save to disk and click start _Windows App Certification Kit_
8. Look at the report.

**Comment by grauwoelfchen** [comment]
@zdavatz Ich habe einen Script für Release Bulid und `appx` Packaging gemacht. Es geht jetzt nur für Debug Build.
Ich denke, wenn wir die Apps mit richtige Certificate File (pfx) build machen, dann wir auch Appx für Release generieren können. So, dann besprechen wir über Certificate auf #150.
