### ISSUE TITLE
Arztadresse anzeigen braucht einen Neustart vom App.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#112]
1. Auf _Arztadresse hinzufügen_ klicken.
2. Artzadresse ausfüllen.
3. _Speichern_ klicken.
4. Arztadresse wird nicht angezeigt.
5. App neu starten.
6. Arztadresse wird angezeigt.

**Comment by grauwoelfchen** [comment]
Same with #98 and #99
