### ISSUE TITLE
Change patient.db (contact) location

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#113]
Before the task for csv import #50, Move db location to AppData. (Make it to work, even if user updates application)

**Comment by grauwoelfchen** [comment]
@zdavatz 

Bitte löschst du alte (patient) db files in der Apps.

```powershell
> rm AmiKoWindows/bin/Debug/AmiKo/Data/amiko_patient_de.db -fo
> rm AmiKoWindows/bin/Debug/CoMed/Data/amiko_patient_fr.db -fo
```

**Comment by zdavatz** [comment]
Ok, die alten DBs sind gelöscht.
