### ISSUE TITLE
Zuviel Abstand im Rezept bis zum ersten Medikament.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#116]
![zuviel abstand](https://user-images.githubusercontent.com/4953/42016765-096f20fa-7aad-11e8-9e85-2ab0bdd26995.png)

**Comment by grauwoelfchen** [comment]
@zdavatz Ich kannmomentan  nicht das Problem auf die Apps sehen. Kannst du nochmal `master` pull machen? und versuhst du mal.

**Comment by grauwoelfchen** [comment]
@zdavatz Ich habe einen Kommit gemacht. Es bringt gar nicht Änderung bei Mir, aber vielleicht geht bei Dir. Bitte versuchst du es mal.

**Comment by zdavatz** [comment]
ok, mache ich.

**Comment by zdavatz** [comment]
Jetzt ist es sehr gut! Bravo!! Jetzt ist es perfekt!

**Comment by zdavatz** [comment]
![abstand_ist_jetz_perfekt](https://user-images.githubusercontent.com/4953/42048053-5b447e5c-7b02-11e8-984a-2902c6463c15.png)
