### ISSUE TITLE
Nur einen Klick um Packung hinzuzufügen

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#117]
Zur Zeit braucht es immer zwei Klicks auf die Packung um die Packung dem Rezept hinzuzufügen. Es sollte nur einen Klick benötigen, gleich wie bei macOS.

https://files.slack.com/files-pri/T27F6280H-FBESM3XS5/2018-06-28_08-39-20.mp4

**Comment by grauwoelfchen** [comment]
@zdavatz Ich kann nicht das Problem auch reproduzieren. Wenn du die Apps auf VM versuchst, Ich denke, dass das KeyEvent (Mouse Klick) vielleicht langsam kommt oder nicht richtig kommt.
Hast du  das Problem nicht auf andere Apps wie File Explorer?

**Comment by zdavatz** [comment]
hast Du nur einen Klick um das Medikament hinzuzufügen?

**Comment by zdavatz** [comment]
Nein, in den anderen Apps habe ich das Problem nicht.

Hast Du nur einen Klick um ein Medikament hinzuzufügen? Auf macOS ist es auch nur ein Klick.

**Comment by grauwoelfchen** [comment]
@zdavatz Ich habe jetzt wahrscheinlich das Problem mit [27da3af3103409432f309823d60a888393c70e0e](https://github.com/zdavatz/amiko_csharp/commit/27da3af3103409432f309823d60a888393c70e0e) flicken. Versuchst du es mal. `master`.

**Comment by zdavatz** [comment]
Ein Moment ich versuche es.

**Comment by zdavatz** [comment]
Es klappt. Ja, das ist viel besser! So muss es sein.
