### ISSUE TITLE
Prescription Saving

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#12]

**Comment by zdavatz** [comment]
Den _Save_ Button nur aktiv machen, falls sich etwas geändert hat. Siehe macOS. Sonst kann man den Button nicht anklicken. Ein Rezept kann entweder überschrieben werden oder als neues Rezept gespeichert werden, wenn man an einem Rezept etwas ändert. Siehe Version 3.4 von AmiKo für macOS.
