### ISSUE TITLE
Restore selected section title status on tab switch

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#123]

**Comment by grauwoelfchen** [comment]
It's already done only for prescriptions (current file is selected/highlighted).

**Comment by grauwoelfchen** [comment]
@zdavatz Bitte schaust du es mal

1. Show something Fachinfo in Kompendium
2. Click e.g. `Schwangershaft` in sections list (in right side area)
3. Go to `Rezepte` (This behavior hides WebBrowser in main area)
4. Go back to Kompendium
4. Make sure `Schwangerschaft` is selected

**Comment by zdavatz** [comment]
Nein, das geht nicht zur Zeit.
