### ISSUE TITLE
Gleiches Rezept darf nicht zweimal importiert werden

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#124]
Falls ein Rezept bereits importiert wurde, darf es nicht ein zweites Mal importiert werden. Die Ansicht muss dann direkt zum importierten Rezept wechseln.

1. Windows Explorer öffnen.
2. Zum Desktop gehen und auf ein _.amk_ File Doppelklicken.
3. File wird im AmiKo-Windows geöffnet.
4. Nochmals auf das gleiche File Doppelklicken.
5. AmiKo Windows öffnet sich und zeigt das Rezept an auf welches man doppelt geklickt hat.

Siehe auch https://github.com/zdavatz/amiko_csharp/issues/125

**Comment by grauwoelfchen** [comment]
Done.

`DobleClick` Support is another topic on #125

**Comment by zdavatz** [comment]
👍
