### ISSUE TITLE
Support import/open with invalid patient_id (overwrite patient values in .amk)

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#125]
1. Rezept mit AmiKo macOS erstellen.
2. Rezept auf den Windows Desktop übertragen.
3. Auf dem Windows-Desktop auf das _.amk_ File doppelklicken.
4. Das Rezept öffnet im AmiKo-Windows.
5. AmiKo-Windows neu starten.
6. Den Patienten vom Rezept anwählen.
7. Das Rezept muss jetzt beim Patienten vorhanden sein (nach dem Neustart von AmiKo).
8. Die Patientenadresse muss natürlich auch gespeichert werden, falls Sie im AmiKo-Windows noch nicht vorhanden ist.

**Comment by grauwoelfchen** [comment]
@zdavatz  OK. Ich mache auch Dobuleclick Support auch auf AmiKo Windows.

NOTE:

Wenn du Rezepte von macOS version importierst, trotz sie greiche Patienten Name und Birthdate haben, sie andere Kontakte werden, weil sie verschiedene source (base string) von Hash haben, wie wir schon früher über das besprochen haben. AmiKo iOS und macOS brauchen diese Änderungen.

Wir verwenden schon nicht mehr `SHA256` in AmiKo Windows. Und ich habe Hash Implementation wie Objective-C auf C# gemacht. Es ist kein Problem. Aber, du möchetete auch `LowerCase` (e.g. `zeno.davatz.2.6.1942`) Rule von Source String und einen Format von Birthdate (ohne Zero. e.g. `2.6.1942`).
AmiKo Windows haltet sich schon an diese Regel.

* https://github.com/zdavatz/amiko-osx/issues/43 (Issue auf amiko-osx)
* #81 (Update patient_id Hash implementation)
* #93 (Change GenerateHash to use same value with internal hash implementation of current Obj-C's NSString )

### macOS Version

no lowercase, not formatted birthdate (right now).

* https://github.com/zdavatz/amiko-osx/blob/master/MLPatient.m#L73

### Windows Version

lowercase, formatted birthdate.

* https://github.com/zdavatz/amiko_csharp/blob/master/AmiKoWindows/Source/Contact.cs#L271-L272
* https://github.com/zdavatz/amiko_csharp/blob/master/AmiKoWindows/Source/Interface/AddressBookControl.xaml.cs#L229

**Comment by zdavatz** [comment]
Wenn Du ein .amk File von iOS oder macOS importierst, dann sollte AmiKo Windows wie folgt vorgehen:

1. Vorname, Nachname werden für den Hash _klein_ geschrieben.
2. Gebr. Datum wird von 20.05.1975 zu 20.5.1975.
3. Das geschieht vor dem automatischen Speichern. 
4. Dann speichert AmiKo Windows das Rezept mit dem Patienten im für Windows optimierten Hash.

Somit kommt es nur darauf an, dass der Hash korrekt berechnet wird vor dem Speichern auf AmiKo Windows.

**Comment by zdavatz** [comment]
auf macOS funktioniert der Rezept-Import noch nicht korrekt von Windows. Der Patient wird mehrfach angezeigt. Wenn ich den Patienten auf macOS lösche, dann werden alle Duplikate gelöscht. Das ist komisch.

**Comment by grauwoelfchen** [comment]
@zdavatz 
Wenn AmiKo Windows diese EXTRA Arbeit für jetziges macOS und iOS Version macht, Das `patient_id` (hash value) von das Patient wird anders als original value (in macOS und iOS Version) in `.amk` gespeichert.  Es sieht aus, der Importieren für User von AmiKo Windows geht. Aber, es brecht Konsequenz.

> Vorname, Nachname werden für den Hash klein geschrieben.
> Gebr. Datum wird von 20.05.1975 zu 20.5.1975.

Ist das OK?

**Comment by zdavatz** [comment]
Es macht nichts, wenn der Hash-Value sich ändert für den gleichen Patienten auf AmiKo-Windows. Wichtig ist nur, dass wir auf AmiKo-Windows keine doppelten Patienten haben, siehe: https://files.slack.com/files-pri/T27F6280H-FBK4HL4BZ/2018-07-03_11-30-33.mp4

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Ich mache diese Fallback Solution für Rezepte von iOS und macOS Version.

Dann, AmiKo Windows wird dieses neues Patient in das Adressebuch mit verschiedene `Uid` von `patient_id` Fend im `.amk` File speichern.
Es bedeutet, dass `patient_id` in `.amk` File unzuverlässing ist. Ich denke, dass auch iOS Version und macOS Version gleich Fallback Solution für Rezepte von Windows Version haben sollen.

**Comment by grauwoelfchen** [comment]
Many topics have been mixed into this issue:

See also #129 (Doubleclick) and #127 (List in Addressbook)

**Comment by zdavatz** [comment]
patient_id = hash. Der Hash wird von jeder Plattform generiert und muss dort immer auf den gleichen Patienten zeigen.

**Comment by zdavatz** [comment]
macOS und iOS werden auch die gleiche Implementation machen wie AmiKo-Windows. Auf iOS funktioniert das automatische Speichern schon auf macOS funktioniert es noch nicht.
