### ISSUE TITLE
New contact from imported prescription file is not listed after import

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#127]
Saved, but not listed.

**Comment by grauwoelfchen** [comment]
@zdavatz Bitte versusht du das Commit ` 7806c4d` (neuest auf master) mal.

**Comment by zdavatz** [comment]
Danke, ich habe den versucht, siehe: https://github.com/zdavatz/amiko_csharp/issues/125#issuecomment-402078855
