### ISSUE TITLE
Patient muss mit "Backspace" und Bestätigung gelöscht werden können

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#128]
Ein Patient muss mit "Backspace" und Bestätigung gelöscht werden können.

1. AmiKo Windows öffnen
2. Patientenverwaltung öffnen.
3. Einen Patienten anwählen.
4. _Backspace_ drücken. -> jetzt muss die gleiche Frage kommen wie wenn man "-" drückt.
5. "Alle Rezept von/und PatientIn löschen?"

**Comment by grauwoelfchen** [comment]
@zdavatz Du kannst jezt mit `Backspace` und `ContextMenu` wie gleich Rezepte Liste einen Kontakt auf die Liste löschen.

**Comment by zdavatz** [comment]
Danke, ja das klappt gut!
