### ISSUE TITLE
Nach Doppelklick oder Drag-and-Drop Import muss das Rezept auch gespeichert werden.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#130]
1. .amk mit macOS erstellen.
2. .amk ins AmiKo-Windows importieren.
3. Patienten-Adresse wird im AmiKo Windows richtig gespeichert.
4. Das Rezept wird aber nicht gespeichert. Das Rezept muss auch gespeichert werden, ohne dass der User _speichern_ klicken muss. Siehe iOS.
5. Siehe: https://files.slack.com/files-pri/T27F6280H-FBKL7GGLW/2018-07-04_08-53-31.mp4

**Comment by zdavatz** [comment]
Ich muss also mehrere Rezepte für einen Patienten importieren können, ohne dass ich _Speichern_ klicken muss.

**Comment by grauwoelfchen** [comment]
#125

**Comment by grauwoelfchen** [comment]
@zdavatz Und das klingt, das das komische Bug auf deinem Environment ist. Ich kann Rezepte in Liste sehen, und App speichert onhe das Problem. Ich schaue es noch weiter an.

**Comment by grauwoelfchen** [comment]
@zdavatz Kannst du Output.Log auf VS nehmen?

**Comment by zdavatz** [comment]
https://gist.github.com/zdavatz/e77ce75ca42490b96971722c49be5eac
