### ISSUE TITLE
Scrollbar geht nicht bis ganz unten

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#132]
Der Scrollbar sollte bis nach ganz unten gehen. Siehe:

![10-medis-oder-mehr](https://user-images.githubusercontent.com/4953/42272773-83228be2-7f87-11e8-9e98-7a7fd2d9eb17.png)

**Comment by grauwoelfchen** [comment]
Done with fd9587045799ec880d898524b3c1dec974dda0e4
