### ISSUE TITLE
"Wurde bereits importiert" hängt sich auf

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#135]
1. Rezept importieren.
2. Nochmals das gleiche Rezept importieren.
3. Die App hängt sich auf, siehe https://files.slack.com/files-pri/T27F6280H-FBK5S55K6/2018-07-05_15-07-22.mp4

**Comment by grauwoelfchen** [comment]
@zdavatz Wie hast Du die App startet? Mit `BuildAndRun.ps1` Skript?
Ich denke, dass du hast noch etwas einege (alte) Processes hattest.  Bitte versuchst du Neustarten von OS auf VM. (Oder machst du `taskkill /im "AmiKo Desitin.exe"` in PowerShell).
Ich kann nicht momentan es reproduzieren.

Als meine Verständnis, Apps auf Windows hängen sich oft für kein Memory auf.

**Comment by grauwoelfchen** [comment]
@zdavatz Ich habe einen Häck für Minimized Window Activation gelöscht. Versusht du es mal.
