### ISSUE TITLE
Patientendaten werden nicht mehr gespeichert.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#136]
1. AmiKo öffnen
2. Rezept per Drag-and-Drop reinziehen. Mindestens 3 Stück.
3. Patienten-Adressbuch öffnen.
4. Keine Patienten sind vorhanden.
5. Siehe: https://files.slack.com/files-pri/T27F6280H-FBLEPD6SK/2018-07-05_15-11-43.mp4

**Comment by zdavatz** [comment]
Nach dem Neustart ist die Patienten-DB leer.

![nach_neustart_pat_db_leer](https://user-images.githubusercontent.com/4953/42325359-53cbd530-8066-11e8-8457-1a2ca7135279.png)

**Comment by grauwoelfchen** [comment]
It seems that this is same reason with #139

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Ich habe einen Problem für Development Environment gefunden.

Du hast gegen Build oder Setup gekämpft. Wenn du `bin` oder/und `obj` einmal löshst, Du muss auch alte Rezepte im "Roaming" Directory löschen, weil App jedes mal der Existenz der Rezepte prüft.

Das war Grund für das Problem.

## Ordners für AmiKo App

```
# Bitte löschst du die Ordners via Explorer.exe usw.
C:\Users/<USER>/AppData/Roaming/ywesee/AmiKo\ Desitin/amk/<UID von Patient>

# Und auch die Ordners, wenn du noch auch diese __alte__ Ordners hast (Sie sind einfach schon unnötig).
C:\Users/<USER>/AppData/Roaming/ywesee/AmiKo\ Desitin/<UID von Patient>

# (nur jetzt)
<PWD>AmiKoWindows/bin/Debug/AmiKo/*
<PWD>AmiKoWindows/obj/Debug/AmiKo/*
```

Jeztz, wir haben `patient.db` (Adressebuch) in Directory von App. Ich werde auf #113 mit #50 arbeiten.
In Zukunft, Wir können einfach nur diese `Roaming` Directory löschen, wenn wir die App als neu testen möchten. Wir brauchen nicht mehr auch `bin` und `obj` zu löschen.
