### ISSUE TITLE
Subject und Mail-Body hat keinen Text

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#137]
1. Rezept per Email versenden.
2. Subject ist falsch.
3. Mail-Body-Text fehlt noch.
![subject_mailbody_kein_text_vorhanden](https://user-images.githubusercontent.com/4953/42325497-bd9bcc2c-8066-11e8-82dd-eeb8495d2e3f.png)

**Comment by grauwoelfchen** [comment]
See #16

**Comment by grauwoelfchen** [comment]
@zdavatz 

FYI:
Das ”Share" ist wie gleich AirDrop auf macOS. Bitte denkst du mal, man kann nicht Body und Subjekt für Mail geben. Es ist File Sharing. User soll selber machen. AmiKo kann nicht wissen, welche App User verwendet. Es ist allgemeine SHARE funktion.

Ich mache auch direkt Link zur Mail App wie macOS (auf #16).
