### ISSUE TITLE
Nach dem Rezeptimport muss Rezept auch nach Patientenwesel ersichtlich sein.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#139]
1. Rezept von Patient A importieren, welcher noch nicht im AmiKo vorhanden ist.
2. Rezept erstellen für Patient B.
3. Rezept speichern für Patiente B.
4. Adressbuch öffnen und auf Patient A doppelklicken.
5. Jetzt müssen rechts die gespeicherten Adressen erscheinen, sonst ist etwas falsch gelaufen.

**Comment by grauwoelfchen** [comment]
@zdavatz Bitte schaust du #136. Ich denke, dass sie gleiche Probleme sind.
