### ISSUE TITLE
mehrere Rezepte für gleichen Patienten importieren

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#143]
1. Mehrere Rezepte für Patient A importieren.
2. Patient B auswählen.
3. Patient A auswählen. Die Rezepte sind nicht mehr da. Die drei importierten Rezepte werden rechts nicht mehr angezeigt.
4. Siehe https://files.slack.com/files-pri/T27F6280H-FBK72P9CY/2018-07-06_08-52-21.mp4

**Comment by zdavatz** [comment]
Im Verzeichnis
```
C:\Users\zdavatz\AppData\Roaming\Ywesee\AmiKo Desitin\amk
```
habe ich alles gelöscht.

**Comment by zdavatz** [comment]
Das ist mein Log: https://gist.github.com/zdavatz/ffe0d532b9315133058017e8ba05d0f8

**Comment by zdavatz** [comment]
Aber wenn ich im Adressbuch die Adresse vom Patienten wechsle, dann sehe ich das Rezeptarchiv rechts mit allen importierten Rezepten vom Patienten nicht mehr.

**Comment by zdavatz** [comment]
Nach einem Neustart der App fehlt das Rezept-Archiv pro Patient auch.

**Comment by zdavatz** [comment]
Warum werden hier nicht gleich viele Ordner wie Patienten
![mehr_ordner_als_patienten](https://user-images.githubusercontent.com/4953/42380619-d7a536bc-812e-11e8-9a96-ee5b7fbac185.png)
 angezeigt?

**Comment by zdavatz** [comment]
Wieso wird die Patiente-DB hier gespeichert?
```
C:\Users\zdavatz\Documents\VisualStudio\amiko_csharp\AmiKoWindows\bin\Debug\AmiKo\Data
```

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Ich habe einen Grund des Problem gefunden. Deine diese Rezept haben falsche (alte) `patient_id`. Der Speichern der Adresse von Kontakt geht (Weil wir schon extra Support für Adresse von diese Rezepte gemacht haben, sie falsche `patient_id` haben.), aber es macht noch Ordner mit falsche `patient_id`. Darum ist die Liste leer. Ich behebe das Issue.

**Comment by grauwoelfchen** [comment]
@zdavatz Das Problem passiert schon nicht mehr. Aber bitte löschst (reset) du einmal alte (mit falsche `patient_id`) Ordners. Ich habe jetzt in REDAME geschrieben, wie man das macht.

Siehe (Contacts and Prescriptions Section für **Reset**)
https://github.com/zdavatz/amiko_csharp#contacts-and-prescriptions

Commit https://github.com/zdavatz/amiko_csharp/commit/f99b09ba210839f5efe8adfd14ffd36203dd6d7a korrigiert das Issue.

**Comment by zdavatz** [comment]
Wenn ich diese drei Befehle ausführe, dann kriege ich wieder den folgenden Error:
![compile_error](https://user-images.githubusercontent.com/4953/42434949-4a997692-8355-11e8-8046-b354e3d50c0a.png)

**Comment by zdavatz** [comment]
Dann mache ich wieder
```
Install-Package MahApps.Metro
```
und dann läuft es wieder.
![install_mahapp](https://user-images.githubusercontent.com/4953/42435131-eb9d633c-8355-11e8-8143-891f345923d1.png)
Das finde ich komisch.
