### ISSUE TITLE
Klicke auf "Senden" soll direkte "Teilen" Menu aufrufen

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#144]
1. Erstelle ein Rezept
2. Klicke auf _Senden_
3. Es braucht kein Kontext-Menu mit "Mail" und "Teilen". Wenn man auf "Senden" klickt, dann sollte direkt das "Teilen" Menu aufgehen mit "Mail" und "OneNote".
![klick-auf-senden](https://user-images.githubusercontent.com/4953/42364410-5a207702-80fb-11e8-8ad3-bbc40cb47195.png)

**Mail geht auf mit Email-Body, Subject, Adresse und Attachment. Das funktioniert sehr gut, Danke!**

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Dann lösche ich `Mail` Menu Item und direkt Mail Link Funktion.

**Comment by zdavatz** [comment]
Ja, gerne bitte. Den "Senden" Button direkt mit "Teilen" verknüpfen.
