### ISSUE TITLE
Wenn ich zwei Mal das gleiche Rezept importiere hängt sich AmiKo Windows auf

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#145]
1. Rezept A importieren.
2. Rezept B importieren.
3. Rezept C importieren.
4. Noch einmal Rezept A importieren.
5. AmiKo Windows hängt sich auf. Ich kann nicht mehr "Ok" klicken.

![zwei-mal-gleiches-rezept-importieren](https://user-images.githubusercontent.com/4953/42435350-822836f6-8356-11e8-92de-96d4e4f4aa05.png)

**Comment by grauwoelfchen** [comment]
@zdavatz Ich denke, dass das Problem von Windows ist. Bitte versusht du es noch mal. Bi mir, es passiert oft auch auf andere Apps auf Windows.

In AmiKo, man kann mehrmals gleiche Rezepte importieren. Es schlagt (existing) Rezepte nach, darum es macht nichts im Wirklichkeit. Deshalb, es hängt nicht  das mit unserer App zusammen, denke ich.
