### ISSUE TITLE
MahApps Error after last commit

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#147]
This commit 78aa62ccbb443c5a73aa958ac815 broke my csproj File again.

![changes_csproj](https://user-images.githubusercontent.com/4953/42440185-3ee0c66a-8365-11e8-8793-043eaf38008e.png)

[diff.txt](https://github.com/zdavatz/amiko_csharp/files/2175345/diff.txt)

**Comment by zdavatz** [comment]
Ich mache:
1. Im git bash: git pull
2. Im powershell: ```PowerShell.exe -ExecutionPolicy Bypass -File .\BuildAndRun.ps1 "AmiKo"```

**Comment by grauwoelfchen** [comment]
```
git checkout -- AmikoWindows/AmikoDesitin.csproj
git checkout -- AmikoWindows/Packages.config
git checkout -- AmikoWindows/packages.config
```

**Comment by grauwoelfchen** [comment]
`Packages.config` and `packages.config`

**Comment by grauwoelfchen** [comment]
`ls -la AmiKoWindows`

**Comment by zdavatz** [comment]
![lsla](https://user-images.githubusercontent.com/4953/42441037-93d231c0-8367-11e8-901f-e104f5d118fe.png)

**Comment by zdavatz** [comment]
``` PowerShell.exe -ExecutionPolicy Bypass -File .\BuildAndRun.ps1 "AmiKo"```

**Comment by zdavatz** [comment]
![error](https://user-images.githubusercontent.com/4953/42441134-d758672a-8367-11e8-874c-7dc386b3491e.png)

**Comment by grauwoelfchen** [comment]
`NuGet.exe install "AmiKoWindows/packages.config"`

**Comment by grauwoelfchen** [comment]
https://www.nuget.org/downloads

**Comment by grauwoelfchen** [comment]
```
rm -fr .vs
```

**Comment by zdavatz** [comment]
![nuget_install](https://user-images.githubusercontent.com/4953/42441437-7927264a-8368-11e8-84ab-7ed11938c483.png)

**Comment by zdavatz** [comment]
![build_error_nuget](https://user-images.githubusercontent.com/4953/42441525-b288c7d6-8368-11e8-9441-9e6b63b2b549.png)

**Comment by zdavatz** [comment]
Das geht **nicht** bei mir
```
rm -fr .vs
```

**Comment by zdavatz** [comment]
Jetzt öffne ich Visual Studio und mache
```
Install-Package MahApps.Metro
```

**Comment by zdavatz** [comment]
Jetzt mache ich
```
 PowerShell.exe -ExecutionPolicy Bypass -File .\BuildAndRun.ps1 "AmiKo"
```

**Comment by zdavatz** [comment]
[diff_2.txt](https://github.com/zdavatz/amiko_csharp/files/2175451/diff_2.txt)
