### ISSUE TITLE
Prepare valid signing certificate

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#150]

**Comment by zdavatz** [comment]
Ich habe ein Appx generiert in 
```
 C:\Users\zdavatz\Documents\VisualStudio\amiko_csharp\AmiKoWindows\bin\Release\Output\yweseeGmbH.AmiKo
```

**Comment by grauwoelfchen** [comment]
AmiKoWindows/bin/Debug/Output/yweseeGmbH.AmiKo.Debug/PackageFiles/Data/

**Comment by zdavatz** [comment]
Ich mache
```
PowerShell.exe -File .\MakeRelease.ps1 "AmiKo" "Release"
```

**Comment by zdavatz** [comment]
Hier habe ich kein "Data" directory:
```
C:\Users\zdavatz\Documents\VisualStudio\amiko_csharp\AmiKoWindows\bin\Release\Output\yweseeGmbH.AmiKo\PackageFiles\
```

**Comment by zdavatz** [comment]
Dieses Verzeichnis ist leer:
```
PS C:\Users\zdavatz\Documents\VisualStudio\amiko_csharp\AmiKoWindows\bin\Debug\AmiKo\Data> ls
```

**Comment by zdavatz** [comment]
Hier habe ich keine Appx-Datei:
```
C:\Users\zdavatz\Documents\VisualStudio\amiko_csharp\AmiKoWindows\bin\Debug\AmiKo
```

**Comment by zdavatz** [comment]
[output_11.7.2018.log.txt](https://github.com/zdavatz/amiko_csharp/files/2184546/output_11.7.2018.log.txt)

**Comment by zdavatz** [comment]
https://gist.github.com/zdavatz/1df54086ec85ab1ca20be9337f76afa5

**Comment by grauwoelfchen** [comment]
@zdavatz Appx bei **Release** Build hat auch alle Datenbank Files bei Mir. Also bitte schaust du die Ordners vor dem `MakeRelease` wie normal.

* `AmiKoWindows/Data/de`
* `AmiKoWindows/Data/fr`

```text
# z.B. in `de` müssen diese Datenbank Files sein.

amiko_db_full_idx_de.db
amiko_db_full_idx_de.zip
amiko_frequency_de.db
amiko_frequency_de.db.zip
amiko_report_de.html
drug_interactions_csv_de.csv
drug_interactions_csv_de.zip
```

Appx bei Release Build zeigt bei Mir `181MB`. Es geht ohne Problem.

**Comment by grauwoelfchen** [comment]
@zdavatz So, wir schon kein Problem für Certificate File (das ist Theme der Issue) haben. wenn du etwas noch Problem bei Dir hast (z.B. Datenbank Files), dann besprechen wir über Store Release (Appx Build) weiter auf #155

**Comment by zdavatz** [comment]
ok
