### ISSUE TITLE
Ich sehe keine Voll-Text-Favoriten

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#152]
Ich sehe nach wie vor keine Voll-Text-Favoriten.

![keine_volltext_favoriten](https://user-images.githubusercontent.com/4953/42556044-996155b0-84ea-11e8-83fe-6dce4ff78e82.png)

**Comment by zdavatz** [comment]
In dieser Kombination stürzt die App immer noch ab.

**Comment by zdavatz** [comment]
Das ist der Crash: https://files.slack.com/files-pri/T27F6280H-FBMU02EAV/2018-07-11_09-14-20.mp4

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Ich schaue es mal wieder an. Kannst du auch `favorites.txt` und ` favorites_fts.txt` in Directory von App Hier mit Output File von Debugview.exe hochladen?

* `C:\Users\<user>\AppData\Roaming\ywesee\AmiKo Desitin\favorites.txt`
* `C:\Users\<user>\AppData\Roaming\ywesee\AmiKo Desitin\favorites_fts.txt`

**Comment by zdavatz** [comment]
[favorites.txt](https://github.com/zdavatz/amiko_csharp/files/2183363/favorites.txt)
[favorites_fts.txt](https://github.com/zdavatz/amiko_csharp/files/2183364/favorites_fts.txt)

**Comment by zdavatz** [comment]
Das ist der Debug Output: https://gist.github.com/zdavatz/dc0a2a12bde9d9b017f86af7fd686d49

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Dein Problem kommt aus `favorites_fts.txt`. Ich untersuche es, wieso das File Problem hat.

**Comment by zdavatz** [comment]
Ok Danke. Ich habe die Favoriten gelöscht. Jetzt klappt es besser.
