### ISSUE TITLE
Warum funktioniert hier die Suche nicht?

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#153]
1. App öffnen
2. Schnell "Ponsta" eingeben.
3. Nach einer kurzen Weile wird das Suchresultat zurückgesetzt.

https://files.slack.com/files-pri/T27F6280H-FBN992XS8/2018-07-11_10-51-59.mp4

und noch ein Video-Beispiel:

https://files.slack.com/files-pri/T27F6280H-FBN9AP3TN/2018-07-11_10-55-16.mp4

wenn ich einen Buchstaben aus der Suche lösche, dann geht es wieder.

**Comment by grauwoelfchen** [comment]
@zdavatz  Bitte schaust du **Status Bar** （☆ spinner in Bottom Bar). Ich denke, dass du noch nur ein bisschen warten musst. Such Resultat kommnt ein bisschen langsam.

**Comment by grauwoelfchen** [comment]
@zdavatz Das Commit oben kann vielleicht ein bisschen besser werden.
