### ISSUE TITLE
Store Release 1.0.7.0

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#155]

**Comment by grauwoelfchen** [comment]
@zdavatz  Ich denke, dass du private (user) **csproj** File hast. Wenn du das hast, bitte schickst du mir es auf **Slack**. Diese File sind (privat) Settings für dich. Die können vielleicht etwas Problem für Datenbank Files haben.

* `AmiKoWindows/AmiKoDesitin.csproj.user`
* `AmiKoWindows/CoMedDesitin.csproj.user`

**Comment by zdavatz** [comment]
Kann man APPX nicht direkt aus VisualStudio erstellen?

**Comment by grauwoelfchen** [comment]
@zdavatz Ich denke, dass wir momentan es nicht auf VS machen können, weil wir `Desktop App Converter.exe` für Desktop Bridge müssen. Aber du kannst nur Build wie normal machen.

**Comment by zdavatz** [comment]
Ich kriege momentan diesen Error:

<img width="822" alt="bildschirmfoto 2018-07-12 um 09 02 32" src="https://user-images.githubusercontent.com/4953/42617594-8166b1f8-85b2-11e8-961d-9a8defd9c7ff.png">

**Comment by zdavatz** [comment]
siehe:

https://gist.github.com/zdavatz/0682824c29cb865c321ecdf1165332f8

**Comment by zdavatz** [comment]
`Set-ExecutionPolicy Unrestricted` hat geholfen.

**Comment by zdavatz** [comment]
Das ist auch interessant. Desktop-App-Converter ist installiert aber er wird nicht gefunden ;/

<img width="992" alt="bildschirmfoto 2018-07-12 um 09 29 45" src="https://user-images.githubusercontent.com/4953/42618714-33edc23c-85b6-11e8-9d4b-eaf296f5726c.png">

**Comment by zdavatz** [comment]
DotNET 4.6.2 was missing. https://www.microsoft.com/en-us/download/confirmation.aspx?id=53321

**Comment by zdavatz** [comment]
Reference Assemblies fehlen immer noch.

<img width="888" alt="bildschirmfoto 2018-07-12 um 14 41 00" src="https://user-images.githubusercontent.com/4953/42631048-adf22a70-85e1-11e8-8e99-ac62affa0c7e.png">

**Comment by zdavatz** [comment]
Das auch noch: https://www.microsoft.com/de-de/download/confirmation.aspx?id=53345

**Comment by zdavatz** [comment]
Dann kommt wieder: 

<img width="531" alt="bildschirmfoto 2018-07-12 um 14 45 37" src="https://user-images.githubusercontent.com/4953/42631244-462f1456-85e2-11e8-8c16-8bf2b65d9e3b.png">

**Comment by zdavatz** [comment]
Ich habe nur diese Files: 

<img width="878" alt="bildschirmfoto 2018-07-12 um 15 00 43" src="https://user-images.githubusercontent.com/4953/42631967-6663d138-85e4-11e8-9aa0-9b0fb46ba9a6.png">

**Comment by zdavatz** [comment]
VisualStudio will mit 4.6.1 bauen:

<img width="996" alt="bildschirmfoto 2018-07-12 um 15 02 21" src="https://user-images.githubusercontent.com/4953/42632043-a2e0a5a0-85e4-11e8-9556-bfa76d0700ed.png">

**Comment by zdavatz** [comment]
Data ist im richtigen Verzeichnis. Appx ist immer noch zu klein.

<img width="923" alt="bildschirmfoto 2018-07-12 um 16 39 10" src="https://user-images.githubusercontent.com/4953/42636707-21776888-85f2-11e8-98fa-f0725242645b.png">

<img width="974" alt="bildschirmfoto 2018-07-12 um 16 40 27" src="https://user-images.githubusercontent.com/4953/42636816-544407bc-85f2-11e8-9173-6822108865ed.png">

**Comment by grauwoelfchen** [comment]
@zdavatz Bitte Setup/Install machst du .Net Framework 4.6.2 und Tools auf Visual Studio, weil du die Tools (MSBuild.exe usw.) in Visual Studio drinnen zum Build verwendest.

`Tools > Get Tools and Features`.

![tools-menu-on-vs-20180712](https://user-images.githubusercontent.com/163063/42636714-701feafa-8624-11e8-8577-c31d65c9eac1.png)

**Comment by zdavatz** [comment]
Das geht jetzt alles, nur das APPX ist jetzt immer noch zu klein.

**Comment by grauwoelfchen** [comment]
@zdavatz Ich denke, dass dein Build von App etwas nicht geht. Bitte schaust du Output und Build Log mal.

Kannst du `BuildAndRun.ps1` mit `"Release"` ohne Warning und Fehler wirklich machen?

**Comment by zdavatz** [comment]
Ich installiere noch so:

<img width="1243" alt="bildschirmfoto 2018-07-12 um 16 45 05" src="https://user-images.githubusercontent.com/4953/42637090-f68e586a-85f2-11e8-8536-7acb17bfbf0b.png">

**Comment by grauwoelfchen** [comment]
@zdavatz Wenn du selber richtig Setup nicht machen kannst, Ich kann einfach Dir Binary von Appx schicken, weil ich bald keine Zeit haben werde, Setup bei Dir unterstützen.

**Comment by grauwoelfchen** [comment]
@zdavatz Bitte versuchst du zuerst nur **Build** mit Datenbank. Du kannst vielleicht `bin` und `obj` Directories einmal löschen (putzen).

**Comment by grauwoelfchen** [comment]
@zdavatz 

### .Net Framework v.4.6.2

Du hast noch Fehlern für Installation.
https://github.com/zdavatz/amiko_csharp/issues/155#issuecomment-404411721

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\Microsoft.Common.CurrentVersion.ta
rgets(1179,5): error MSB3644: Die Verweisassemblys für Framework ".NETFramework,Version=v4.6.2" wurden nicht gefunden.
```

Bitte versuchst du mal `MSBuild.exe` von Hier:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe`. (nicht `C:...\MSBuild\15.0\Bin\amd64` sondern  versuchst du es mal ohne **amd64**). Ich habe keine Ahnung über Unterschied mit `amd64` und ohne `amd64` usw. in die Ordner. Aber, wenn du richtig Frameworks und Tools auf VS installiert hast, sie beides funkziovieren sollen. Der Fehler oben sagt einfach, dass es noch 4.6.2 nicht finden kann.

### DesktopAppConverter.exe

Das zeigt Dir, wo dein `DesktopAppConverter.exe` ist.
```powershell
> Get-Command DesktopAppConverter.exe
```

**Comment by grauwoelfchen** [comment]
@zdavatz So, bitte schaust du zuerst an, ob du mit .NET v4.6.2 ohne Problem Debug Build von `.exe` machen kannst. 
https://github.com/zdavatz/amiko_csharp#using-msbuild

```powershell
> PowerShell.exe -ExecutionPolicy Bypass -File .\BuildAndRun.ps1 "AmiKo"
```

DesktopAppConverter.exe braucht momentan mindestens .Net Framework `v4.6.2`. Aber, du musst zuerst selber feststellen, dass Build ohne Problem geht.

**Comment by zdavatz** [comment]
`C:\Users\zdavatz\AppData\Local\Microsoft\WindowsApps\DesktopAppConverter.exe`

**Comment by zdavatz** [comment]
<img width="844" alt="bildschirmfoto 2018-07-13 um 12 05 45" src="https://user-images.githubusercontent.com/4953/42683151-286d0924-8695-11e8-9958-9703d9ef1168.png">

**Comment by grauwoelfchen** [comment]
@zdavatz Bitte versuchst du `AmiKoWindows/AmiKoDesitin.csproj.user` zu machen.

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <EnableSecurityDebugging>false</EnableSecurityDebugging>
    <VerifyUploadedFiles>false</VerifyUploadedFiles>
    <SignAssembly>false</SignAssembly>                                          
    <GenerateManifests>false</GenerateManifests>                                
  </PropertyGroup>                                           
</Project> 
```
