### ISSUE TITLE
alte Rezepte werden nicht angezeigt.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#162]
1. AmiKo Starten
2. Volltext-Suche klicken.
3. "Kind" Suchen.
4. Resultat wählen.
5. Kapitel wählen.
6. Fachinfo anzeigen mit Highlight.
7. "Rezept" klicken.
8. Patient doppelklicken der bereits Rezepte hat.
9. alte Rezepte werden nicht angezeigt.
10. Auf "Präparat" klicken.
11. Jetzt werden die Rezepte angezeigt.

Siehe: https://files.slack.com/files-pri/T27F6280H-FBQQV6BDG/rezepte_erscheinen_erst_nach_umschlaten.mov

**Comment by zdavatz** [comment]
Ist wohl verwandt mit #160

**Comment by grauwoelfchen** [comment]
@zdavatz Ich denke, dass es nicht das Problem ist, weil `Rezepte` nur für **Präparat** wie macOS Version ist. Bedeutet das, dass du die Rezepte auch für ausser **Präparat** zeigen möchtest?

**Comment by grauwoelfchen** [comment]
@zdavatz Ich habe jetzt einen Commit für #160 und #162 gemacht. Ist das gut?

**Comment by zdavatz** [comment]
Danke, das werde ich testen.
