### ISSUE TITLE
Umschalten von Kompendium zu Rezepte und zurück hängt die App auf

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#163]
1. AmiKo Windows starten
2. Voll-Text-Suche
3. "Kind" suchen.
4. Fachinfo Kapitel anwählen.
5. Fachinfo anschauen.
6. Rezepte klicken.
7. Patient wählen.
8. altes Rezept wählen.
9. Packung löschen.
10. Neues Rezept speichern.
11. Umschalten auf "Kompendium" 
12. Neue Fachinfo anklicken.
13. App hängt sich auf und reagiert nicht mehr.
Siehe: https://files.slack.com/files-pri/T27F6280H-FBRDGG4AH/amiko-windows-hang.mov

**Comment by grauwoelfchen** [comment]
Crash Log: https://gist.github.com/zdavatz/a293b98d917e0804e991f468ae6a46be#file-Windows%20Crash

**Comment by grauwoelfchen** [comment]
@zdavatz Bitte versuchst du neuest Commit mal. Es feht ohne Problem bei Mir mit altest/neuest Datenbank deibes.

**Comment by zdavatz** [comment]
super teste morgen. Danke!
