### ISSUE TITLE
Umschalten zwischen Kompendium, Rezept und Favoriten kann immer noch zum Absturz führen.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#164]
siehe Log: https://gist.github.com/zdavatz/2402b1816206a6daf9559d1419eb2d81

**Comment by grauwoelfchen** [comment]
@zdavatz Ich denke, dass ich das Databank Switching Bug für Fachinfo und Fulltext Such schon mit https://github.com/zdavatz/amiko_csharp/commit/4eb2e28ae7ac584401eb9d8cf1763dfce7013d89 und https://github.com/zdavatz/amiko_csharp/commit/98a6e8cf9ddcecc47f6d7548abd15228ed3b23e4 gelöscht habe.

Aber Store Release noch keine diese Fix hat. Hast du das mit neuest Code versucht?

**Comment by grauwoelfchen** [comment]
@zdavatz Ich denke, dass das Commit oben nicht hilflich für das Problem ist, weil es nicht eigentliches Problem löscht. Aber, bitte versuchst du es mal.

**Comment by zdavatz** [comment]
Ok, ich werde das nochmals testen.
