### ISSUE TITLE
Umsortierung vom gleichen Suchresultat geht nicht mehr.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#165]
1. Klick auf Inhaberin
2. Suche nach "Roche"
3. Alle Roche Produkte kommen.
4. Klick auf "Präparat".
5. Jetzt muss das *_gleiche_* Suchresultat umsortiert werden nach Packungen.

Siehe macOS/iOS. Das hat immer geklappt. Wieso klappt das jetzt nicht mehr? Das ist ein Key-Feature von AmiKo.

**Comment by zdavatz** [comment]
Dafür brauchen wir einen Test. Es kann nicht sein, dass wir einfach Funktionalität verlieren ohne es zu merken.

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Ich schaue es auch mal auf AmiKo Windows an. Ich habe gadacht, dass einen Bug ist, weil das ursprüngliches Problem von UI State/Query Button für Such die Resultaten versteckt. Darum macht die App am momentan immer Suchresultat Clear bei Klick auf Query Buttons.

Und wenn das Fix schwierieg ist, Ich werde alle UI Änderungen und Bug Fix für Fachinfo Such und Fulltext Such, was ich habe gemacht, revert machen. Weil ich das nicht weiss, und dieses mal nur Rezepte und Addressbuch konzentrieren soll.

**Comment by grauwoelfchen** [comment]
@zdavatz Kannst du das Commit oben testen, ob es Verhalten ist, was du eigentlich möchtest. Ich schaue es mal weiter an (auch macOS)
