### ISSUE TITLE
AmiKo fatal Crash i7 

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#169]
`clr_exception_system.argumentoutofrangeexception_80131502_amiko_desitin.exe!unknown
`

See [Microsoft Report](https://partner.microsoft.com/en-us/dashboard/analytics/reports/apphealth/details?productId=9WZDNCRDFFXC&failureHash=78cb39ac-55a8-0c11-2d86-016b29406875&viewSelected=l72h)

[stackTrace.tsv.zip](https://github.com/zdavatz/amiko_csharp/files/2216307/stackTrace.tsv.zip)

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Ich schaue es mal an. Ich denke, dass diese Teilen für Article von Fachinfo/FullText etwas Problem haben.

https://github.com/zdavatz/amiko_csharp/blob/master/AmiKoWindows/Source/Article.cs#L89-L104

**Comment by grauwoelfchen** [comment]
@zdavatz Ich denke, dass das Commit oben das Problem löscht hat. Dann bitte öffnet wieder, wenn das Crash auf Store Release hat.

**Comment by zdavatz** [comment]
Ok. Das werde ich wieder testen mit dem neuen Appx Release. Beim Kunden ist der ganze Computer abgestürzt.
