### ISSUE TITLE
MakeRelease sollte bin und obj Dir immer löschen

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#170]
`MakeRelease` sollte das `bin` und `obj` immer zuerst löschen.

**Comment by grauwoelfchen** [comment]
@zdavatz Es macht schon die Löschen. Siehe Skripten.
https://github.com/zdavatz/amiko_csharp/blob/master/MakeRelease.ps1#L89

Wenn du etwas andere Prozesses hast, die noch diese Ordners verwenden, die Löschen werden scheitern.

**Comment by zdavatz** [comment]
Ok.
