### ISSUE TITLE
Doppelklicken auf Rezept öffnet Rezept nicht im Windows Store AmiKo

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#171]
<img width="683" alt="bildschirmfoto 2018-07-22 um 14 54 10" src="https://user-images.githubusercontent.com/4953/43045316-1db47446-8dbf-11e8-8e8b-078f9c764544.png">

<img width="606" alt="bildschirmfoto 2018-07-22 um 14 50 11" src="https://user-images.githubusercontent.com/4953/43045298-cc972824-8dbe-11e8-9b7f-69557b94b503.png">

Doppelklicken geht noch nicht.

**Comment by zdavatz** [comment]
AmiKo/CoMed muss in dieser Liste auftauchen:
<img width="576" alt="bildschirmfoto 2018-07-22 um 15 09 17" src="https://user-images.githubusercontent.com/4953/43045423-4243bda6-8dc1-11e8-9c7a-1a1abab50492.png">

**Comment by grauwoelfchen** [comment]
@zdavatz Ich denke, dass das Commit oben wieder Icon für DoppelKlick und die Liste zum öffnen macht. Dann schauen wir es mal. (Ich habe `FileAssociation` für Store Release Packs hinzugefügt)

Du kannst es testen wie folgende steps:

* Uninstall alle `AmiKo` und `CoMed` apps aus **Apps**
* Löschen built Apps in `AmiKoWindows/bin` und `AmiKoWindows/obj`
* Check `.amk` File ohne Amiko App __nicht__ zu öffnen
* Build mit `MakeRelease.ps1` (z.B. "Debug" Option installiert die App automatisch)
* Check `.amk` File zu öffnen.

**Comment by zdavatz** [comment]
Ich mache `PowerShell.exe -ExecutionPolicy Bypass -File .\BuildAndRun.ps1 "CoMed" "Debug"`

und erhalte immer noch das Folgende:

**Comment by zdavatz** [comment]
<img width="1116" alt="bildschirmfoto 2018-07-23 um 14 43 26" src="https://user-images.githubusercontent.com/4953/43074711-e08b81ae-8e86-11e8-860a-2ed8fbbfd091.png">

**Comment by grauwoelfchen** [comment]
@zdavatz Ich denke, dass es bedeutet, was du noch Application Association auf OS nicht löschen. Und normallerweise zeigt es nicht schmutzige Pfad wie Screenshot, wenn man mit `.exe` oder `.appx` File öffnet.

Bitte löschst du einmal alte (jetziges) File Associtation, und versuchst du `MakeRelease.ps1` Skript mit `"Debug"`. `BuildAndRun.ps1` hängt nicht `Appx`, sondern macht nur `.exe` File.

**Comment by grauwoelfchen** [comment]
@zdavatz Und wenn du es richtig gemacht hast, Alle File Favicons von `.amk` werden gleich wie AmiKo Desitin App.

**Comment by zdavatz** [comment]
Kann man die alte File-Assoziation nicht überschreiben?

**Comment by zdavatz** [comment]
Wo lösche ich die File Assoziation? `HKEY_CLASSES_ROOT` hat keinen `.amk` Eintrag.

**Comment by zdavatz** [comment]
Ich habe ja so gemacht: `PowerShell.exe -ExecutionPolicy Bypass -File .\BuildAndRun.ps1 "CoMed" "Debug"`

**Comment by grauwoelfchen** [comment]
@zdavatz Nein. Du musst Appx Package machen. Bitte lässt du **MakeRelease.ps1**  (nicht **BuildAndRun.ps1**) laufen.

**Comment by zdavatz** [comment]
Ok, werde ich testen.
