### ISSUE TITLE
Rezept mit DAD importieren ohne Artzadresse führt zu Crash

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#172]
1. AmiKo Starten, ohne gespeicherte Arztadresse.
2. Rezept per Drag and Drop importieren.
3. AmiKo stürzt ab.
4. Siehe auch #169

**Comment by zdavatz** [comment]
Die App stürzt auch ab wenn man das Folgende tut:
1. App starten, ohne Arztadresse.
2. Rezept importieren, mit Drag and Drop.
3. Am Rezept etwas ändern.
4. Speichern klicken. 
5. App stürzt ab.

**Comment by zdavatz** [comment]
Ohne eigene Arztadresse sollte man nicht importierte Rezepte speichern können. Der "Speichern" Button sollte dann deaktiviert sein.

**Comment by grauwoelfchen** [comment]
@zdavatz Dann zeigt die App jetzt nicht `Speichern` Button ohne gespeichert Arztadress, wenn man Komment oder neues Medikament hinzufügt.

**Comment by zdavatz** [comment]
Genau, sehr gut.

**Comment by zdavatz** [comment]
Siehe #174  Drag and Drop klappt nicht mehr. Damit kann ich das nicht testen.

**Comment by grauwoelfchen** [comment]
@zdavatz Welche App versuchst du jetzt mal? Appx oder Exe (und Debug oder Release)?

**Comment by grauwoelfchen** [comment]
@zdavatz Du hast **DEINE** Settings nur AmiKoDesitin.csproj Commit gemacht. Aber im Screencast auf #174 versuchtst du `CoMed`. (Wie ich früher mehr mal so gesagt habe, es ist nicht gut)
https://github.com/zdavatz/amiko_csharp/commit/ee74d74a1214c54e68c6a4ffb4618f5b3af01107#diff-786c37cdfacb7bdcfd638107231268d3

Wenn diese änderungen bei wichtig ist, bitte versuchst du diese Änderungen auch zu `CoMedDesitin.csproj` zu hinzufügen.

**Comment by zdavatz** [comment]
Diese Änderungen sind nur für Release aus VS.
