### ISSUE TITLE
Drag and Drop is not working anymore.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#174]
Siehe: 
https://files.slack.com/files-pri/T27F6280H-FBWEUA2BG/draganddropnotworkinganymore.mov

**Comment by zdavatz** [comment]
So kann ich den Import nicht mehr testen.

**Comment by grauwoelfchen** [comment]
@zdavatz Bei mir, `.appx` und `.exe` beides gehen gut auch Drag and Drop. Bitte ladest du Debug log hoch.

**Comment by zdavatz** [comment]
Gut, dann mach bitte weiter und ich teste in der .appx Version welche Du hochladen wirst.
