### ISSUE TITLE
AppX 1.0.8.0 erstellen und hochladen

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#175]
Sobald du fertig bist mit allen Issues, bitte Version 1.0.8.0 erstellen und in den Windows Store hochladen für _AmiKo_ und _CoMed_.

Dann werde ich den Release machen und wieder alles testen.

**Comment by grauwoelfchen** [comment]
@zdavatz Done. Und auch App Icon auf Windows Store Dev Center ist zurück wie normal. ;)

* AmiKo -> Submission 6 (1.0.8.0)
* CoMed -> Submission 5 (1.0.8.0)

Sie (beides) sind noch **Not submitted**, aber schon **Validated**. So, schauen wir dann es mal, ob das Problem auf #169 nicht passiert.

Und du kannst diese Appx Files auch von Hier nehmen:
https://dl.grauwoelfchen.net/data/amiko/windows/1.0.8.0/

**Comment by zdavatz** [comment]
Danke! Ich mache jetzt _submit_ und dann teste ich wieder mit der App aus dem Store.
