### ISSUE TITLE
pfx certificate into Trusted People on Local Machine via Certificate Wizard.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#176]
Wie geht der Befehl dafür?

`You need to install this pfx certificate into Trusted People on Local Machine via Certificate Wizard.`

**Comment by grauwoelfchen** [comment]
@zdavatz  Wie ich auf Slack gesagt habe, du kannst einfach das `.pfx` (Certificate File) Double Click machen. Dann Wizard Window commit.

**Comment by zdavatz** [comment]
ok, werde ich machen.

**Comment by zdavatz** [comment]
this helps: https://github.com/zdavatz/amiko_csharp#3-re-signing
