### ISSUE TITLE
Voll-Text/Kompendium Favoriten werden nicht immer (alle) angezeigt.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#177]
1. AmiKo starten
2. _Interaktionen_ klicken.
3. _Favoriten_ klicken.
4. Präparat-Favoriten werden angezeigt.
5. _Voll-Text_ klicken.
6. Voll-Text Favoriten werden nicht angezeigt.
7. _Kompendium_ klicken.
8. _Favoriten_ klicken. 
9. Jetzt werden die _Voll-Text_ Favoriten angezeigt.

Das gleiche geschieht auch mit den "Präparate" Favoriten.

**Comment by zdavatz** [comment]
Das ist auch komisch. Ich suche etwas aber es werden alle Medikamente angezeigt.
![ponstan](https://user-images.githubusercontent.com/4953/44525344-f9490f00-a6e0-11e8-812b-6a01da8a26bd.jpg)

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Ich habe verstanden, was du meinst. Ja, das ist vermutlich ein bisschen komisch. Man muss jetzt mindestens einmal `Volltext` auf `Kompendium Tab klicken, Volltext-Resultat mit Favoriten zu zeigen. Ich schaue es mal.

**Comment by zdavatz** [comment]
werde es versuchen.
