### ISSUE TITLE
Version 1.0.9.0 hat immer noch zwei Crashes

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#178]
Siehe [partner.microsoft.com](https://partner.microsoft.com/en-us/dashboard/analytics/reports/apphealth?productId=9WZDNCRDFFXC)

**Comment by grauwoelfchen** [comment]
@zdavatz Warten wir noch es weiter.

Ich denke, dass es nicht unklar ist, ob diese zwei Crash mit Kode von AmiKo zusammenhängen, weil das Report keinen Info hat. Und wenn App etwas Problem drinnen hat, man kann Stacktrace wie Log Output sehen, wie wir früher für `1.0.6.0` und `1.0.7.0` gesehen haben. Ich denke, dass das auch Counts für etwas Problem von Issue auf OS oder andere User-Fehlers zeigt.

Das sagt:

```
Includes all failures where we can’t determine the failure name (due to storage constraints, user privacy settings, etc.)
```

**Comment by zdavatz** [comment]
Ok, Danke, warten wir noch ein bisschen.

**Comment by zdavatz** [comment]
Version 1.0.9.0 hat immer noch einen Bluescreen-Crash:
1. App aus Store installieren
2. App starten
3. Windows Bluescreen
4. Ganzes Windows stürzt ab

**Comment by zdavatz** [comment]
Und noch mehr Crashes. https://partner.microsoft.com/en-US/dashboard/analytics/reports/apphealth?productId=9WZDNCRDFFXC

**Comment by zdavatz** [comment]
Wäre es möglich das
```
<TargetPlatformVersion>8.1</TargetPlatformVersion
<TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
```
hochzuziehen?

**Comment by zdavatz** [comment]
Ich denke, die Bluescreens kommen, weil wir eine Microsoft-Lib ansprechen, welche im Kernel drinnen ist. Darum stürzt der ganze Computer ab und nicht nur unsere Software.

**Comment by zdavatz** [comment]
Error Code in Blue-Screen: https://support.microsoft.com/en-us/help/14238/windows-10-troubleshoot-blue-screen-errors

**Comment by zdavatz** [comment]
The client now believes it is his PC that has a problem.
