### ISSUE TITLE
Report für CoMed 1.0.10.0 submission

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#183]
[Report](https://partner.microsoft.com/dashboard/submissions/api/products/9NLLDB9VXMGX/certreport/2000000000017252888) für die CoMed 1.0.10.0 submission sagt: 
```
Notes To Developer
Unfortunately there was an issue with the signing of your app. Please increase the version number in your package, upload the updated package and submit so that the app can be re-signed and certified. 
Tested Devices: Windows 10 Desktop
```

**Comment by grauwoelfchen** [comment]
@zdavatz Ich habe jetzt **nur** `CoMed` (zu `1.0.11.0`) aktualisiert.

```
CoMed (Submission 6) hat `1.0.11.0` in progress
AmiKo (Submission 7) hat `1.0.10.0`, in store (no change)
```

`1.0.10.0` und `1.0.11.0` haben kein Unterschied ausser Version Nummer, weil Sie gesagt haben, dass CoMed etwas Problem in Signing hat. Es ist unklar.

#### Note

Wir verwenden gleichen Skript die Packages (AmiKo, CoMed) zu machen.
Du kannst beide Packungen von `1.0.11.0` von Hier unterladen:
https://dl.grauwoelfchen.net/data/amiko/windows/1.0.11.0/
