### ISSUE TITLE
printing a label with "Dymo 450" label printer: 89x36mm

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#22]
Die Version 3.4.1 von AmiKo für macOS kann jetzt Etiketten drucken in der Grösse von 89x36mm.

<img width="461" alt="bildschirmfoto 2018-05-16 um 13 13 51" src="https://user-images.githubusercontent.com/4953/40113867-2336e086-590b-11e8-9617-9fbe284bc9f7.png">

wenn man hier klickt, dann druckt es die Etikette, 89x36mm.

<img width="641" alt="bildschirmfoto 2018-05-16 um 13 15 42" src="https://user-images.githubusercontent.com/4953/40113956-68eb1d2c-590b-11e8-8e05-766d1bdd6a1b.png">

Das ist getestet mit diesem [Drucker](https://www.amazon.co.jp/SANFORD-BRANDS-1752265-DYMO%E7%A4%BE-%E3%83%A9%E3%83%99%E3%83%AB%E3%83%A9%E3%82%A4%E3%82%BF%E3%83%BC450%E3%82%BF%E3%83%BC%E3%83%9C-%E9%AB%98%E9%80%9F%E3%83%A9%E3%83%99%E3%83%AB%E3%83%97%E3%83%AA%E3%83%B3%E3%82%BF/dp/B0027JIIKQ).

Siehe auch Issue [16](https://github.com/zdavatz/amiko-osx/issues/16) von macOS.

**Comment by zdavatz** [comment]
Punkt [19](https://github.com/zdavatz/amiko_csharp/wiki/Rezeptfunktion-f%C3%BCr-AmiKo-auf-Windows-10) im Wiki.

**Comment by grauwoelfchen** [comment]
@zdavatz habe gemacht. Ich denke, dass es ein bissschen besser als Label auf jetziges macOS Version (Margin, Multi-Line Support, Text-Extraction usw.) ist. Aber sonst, es ist meistens gleich. Aber, Ich habe kein Printer. Bitte versuchst du es mal fe5935027941b744b2193979eeda2603b1b9ddea

![medication-label-20180707](https://user-images.githubusercontent.com/163063/42419201-ebb80a4a-82ea-11e8-9465-5bc0624de09e.png)

**Comment by zdavatz** [comment]
Danke, das werde ich testen.

**Comment by zdavatz** [comment]
Das sieht gut aus. Ich werde es auf dem Label-Printer noch testen. Falls dort ein Problem auftaucht, werde ich Dir mitteilen.
