### ISSUE TITLE
Rezept, Arztunterschrift, Patienten, Favoriten in der Cloud speichern

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#227]
Rezept, Arztunterschrift, Patienten, Favoriten in der Cloud speichern. Was ist besser für Windows? Gdrive oder OneDrive?

**Comment by zdavatz** [comment]
Es sieht so aus, als gibt es für OneDrive seit drei Jahren kein Upate. Also nehmen wir Gdrive.

**Comment by b123400** [comment]
Meine Todo-Liste:

- [x] Login mit Google
- [x] Logout
- [x] AMK Dateien hochladen
- [x] AMK Dateien runterladen
- [x] favorite.json
- [x] favorite-full-text.json
- [x] Patienten hochladen
- [x] Patienten runterladen
- [x] Arzt hochladen
- [x] Arzt runterladen
- [x] UI
- [ ] Memory leak reparieren
- [ ] PatientenListe updaten wenn gibt es neue Patienten
- [ ] API Key konfigurieren

**Comment by zdavatz** [comment]
Das sieht gut aus! Danke dir!
