### ISSUE TITLE
App stürzt ab nach Google Sync mit Android

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#235]
1. Mit Android bei Google Drive anmelden mit AmiKo.
2. Favoriten, Arztunterschrift, Rezept erstellen.
3. Synchronisieren.
4. Auf Windows AmiKo App neu installieren.
5. Mit Google Sync einloggen.
6. Windows App stürtzt ab/kann nicht gestartet werden.
7. Finde auch den Ordner `ywesee` nicht in `C:/Users/zdavatz/AppData/Roaming`

<img width="659" alt="Bildschirmfoto 2020-07-12 um 19 44 16" src="https://user-images.githubusercontent.com/4953/87251981-5e927e80-c478-11ea-9cd4-76618dd130b2.png">

**Comment by zdavatz** [comment]
Kann es sein, dass Google-Sync das Verzeichnis 
<img width="292" alt="Bildschirmfoto 2020-07-12 um 20 21 27" src="https://user-images.githubusercontent.com/4953/87252629-4709c480-c47d-11ea-96f4-c9f26090db90.png">
nicht erstellt, falls es noch nicht da ist?

**Comment by zdavatz** [comment]
Ich habe jetzt Favoriten und Rezepte auf Windows erstellt, aber sehe nach wie vor keinen Ordner `C:/Users/zdavatz/AppData/Roaming/ywesee/AmiKo`
<img width="1144" alt="Bildschirmfoto 2020-07-12 um 20 27 00" src="https://user-images.githubusercontent.com/4953/87252743-360d8300-c47e-11ea-839b-b9486dd15aa8.png">

**Comment by b123400** [comment]
Es scheint dass, wenn die App is aus Microsoft Store runtergeladen, es benutzt anderer Ordner. z.B. `C:\Users\User\AppData\Local\Packages\yweseeGmbH.AmiKo_nd9tjf228athe\LocalCache\Roaming\ywesee\AmiKo Desitin`
