### ISSUE TITLE
Drag und Drop von AMK Dateien klappt nur bei neu erstellen Rezepten.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#236]
1. Patient erstellen A.
2. Rezept erstellen AA.
3. Rezept AA speichern.
4. Rezept AA aus dem Archiv auf den Schreibtisch ziehen.
5. Patient A mit allen Rezepten löschen.
6. Rezept AA vom Schreibtisch wieder ins AmiKo ziehen. Patient A mit Rezept AA sollten jetzt wieder erstellt sein.

**Comment by b123400** [comment]
![screencast 2020-10-25 23-17-03](https://user-images.githubusercontent.com/127193/97109831-dd09e800-1718-11eb-83d7-15bf77890bf0.gif)

Ich habe es versuchen, aber es klappt.

**Comment by zdavatz** [comment]
Hast Du speichern geklickt bevor Du Drag and Drop machts?

**Comment by zdavatz** [comment]
Bei mir klappt es gar nicht:

![2020-10-26_09-12-46](https://user-images.githubusercontent.com/4953/97148614-b7f29500-176b-11eb-997a-5402be798632.gif)

**Comment by zdavatz** [comment]
@bettar reports that it also does not work on his Windows 10 Machine.

**Comment by zdavatz** [comment]
Ok, es klappt auch bei mir aber nur bei den neuen Rezepten.
