### ISSUE TITLE
Patient hash in amk file

### ISSUE THREAD

**Issue by bettar** [zdavatz/amiko_csharp#237]
I just created an amk file with the latest version of AmiKo Desitin installed from the Microsoft Store. I was expecting that the patient ID is calculated with the sha256 algorithm, according to [Issue #81](https://github.com/zdavatz/amiko_csharp/issues/81) but when I inspected the file it had a much shorter patient hash.

**Comment by zdavatz** [comment]
Thank you for reporting this. This has to be fixed.
