### ISSUE TITLE
Provide Windows ARM build for Windows store.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#251]
1. Install Windows 11 on Mac M1 with UTM: https://mac.getutm.app/ (the latest DMG file is provided for free on the github page). 
```
Download the SPICE Guest Tools ISO (https://mac.getutm.app/support/) and attach it to the VM. Then press Shift+F10 in the VM to open a command prompt. Go to D:\ by typing D: and run the setup exe located in the ISO. If you reboot you'll see a network connection has been added.
```
2. Windows 11 ARM build is also provided for free.
3. Launch the Windows App Store and try to install `AmiKo Desitin`
4. App does not install, because we are missing the ARM build.
5. Try to build the ARM binaries in the APPX package, that is now already generated with every new release.

**Comment by zdavatz** [comment]
1. Clicking "Install" in the Browser on Win11 Arm (Mac Mini with M1 and UTM) nothing happens.
2. Uploading Bildschirmaufnahme 2022-04-05 um 09.09.08.mov…

**Comment by b123400** [comment]
I tried to run Microsoft Store on Windows 11 Arm, and nothing happens.

https://user-images.githubusercontent.com/127193/161735221-7c09bc6b-28a2-41f4-888d-cb1ddcd4a6a6.mp4

**Comment by zdavatz** [comment]
1. I downloaded the MSI from here: https://dev.azure.com/ywesee/ba81e183-7062-4bc3-ba48-c02555b9e1b8/_apis/build/builds/103/artifacts?artifactName=drop&api-version=7.0&%24format=zip
2. Appx does not seem to be signed, that is obviously done by the Microsoft store.
3. MSI installs on ARM as X86, but does not start.
4.![Bildschirmfoto 2022-04-05 um 15 28 57](https://user-images.githubusercontent.com/4953/161765686-40c2c826-fb69-4c5d-9339-b7ec6e30e379.png)
5. https://user-images.githubusercontent.com/4953/161765716-d5b3853f-9cf8-4940-9060-5798fcdb028c.mov
6. ARM Dir does not show installation ![Bildschirmfoto 2022-04-05 um 15 27 21](https://user-images.githubusercontent.com/4953/161765898-8d0f5b0f-84c9-42e7-b749-09cd3bbf0859.png)

**Comment by zdavatz** [comment]
@b123400 hast Du das schon probiert: https://kb.parallels.com/128520

**Comment by zdavatz** [comment]
1. After running `wsreset.exe -i` I can install the App via den Windows Store.
2. When updating the App, the App hangs though:
3. https://user-images.githubusercontent.com/4953/161931169-dd2b46fa-1141-41bc-8221-96df72528a70.mov
4. It seems to use a lot of Memory and CPU
5. ![PNG-Bild](https://user-images.githubusercontent.com/4953/161931238-daabbbd4-9f15-4d15-b032-b396d410738f.png)
