### ISSUE TITLE
Fix JavaScript Loading Problem on Section Title Click Event

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#29]

**Comment by zdavatz** [comment]
Woher kommt dieser Error? Der war vorher nicht da.
![win_10_error](https://user-images.githubusercontent.com/4953/40295579-16f1734a-5cda-11e8-9cc5-ed2e4e99c359.jpg)

**Comment by zdavatz** [comment]
woher kommt dieser Bug? Der war vorher nicht da.
