### ISSUE TITLE
Layout dummy window/controls for prescriptions

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#30]
Put dummy view parts like window and controls for prescriptions.

**Comment by grauwoelfchen** [comment]
![dummy-precsription-controls-20180521](https://user-images.githubusercontent.com/163063/40295616-ec4fac48-5d14-11e8-964a-9786a666fc48.png) (progress)

**Comment by zdavatz** [comment]
Ist dieser View XAML basiert?

**Comment by grauwoelfchen** [comment]
Ja. Natürlich.

https://github.com/zdavatz/amiko_csharp/commit/5227a9c212e4c3f8643d26699f208748c33178f7#diff-3cb0c44051d1bbad50b802c0dc8e4613L49

**Comment by zdavatz** [comment]
Werden die Buttons im View auch mit XAML generiert?

**Comment by grauwoelfchen** [comment]
![dummy-controls-on-prescription-view-20180522](https://user-images.githubusercontent.com/163063/40356648-a88ee04c-5df4-11e8-9b0c-dde6d8256690.png)
(progress 1)

![dummy-modal-window-for-patient-search-20180522](https://user-images.githubusercontent.com/163063/40356655-b15a4a90-5df4-11e8-9e5d-c4e66a16085f.png)
(progress 2)

**Comment by zdavatz** [comment]
Werden die Buttons im View auch mit XAML generiert?

**Comment by zdavatz** [comment]
Also, wie ich schon gesagt habe, würde ich es besser finden wenn wir hier kein neues Floating-Fenster öffnen (ein neues Fenster ist zu unruhig). Ich würde es besser finden, wenn wir wie bei macOS einen Fly-Out machen, siehe: https://docs.microsoft.com/de-de/dotnet/api/microsoft.toolkit.uwp.ui.controls.expander?view=uwp-toolkit-dotnet

**Comment by zdavatz** [comment]
Schritte zum Reproduzieren sind wie folgt:
1. User klickt auf: "Patient Suchen"
2. Der Fly-Out geht gegen unten auf und überlagert die Seite wie bei macOS.

**Comment by grauwoelfchen** [comment]
AmiKo ist nicht UWP, sondern WPF. Und, es läuft als single Browser View auf Main Window. Es funkzioniert normallerweise mit Page Navigation in das Window. Wenn man anderes Window (oder Dialog) machen möchtet,  `Modal` Window ist normal für die Ziel, denke ich.

* [Introduction to WPF](https://docs.microsoft.com/en-us/visualstudio/designers/introduction-to-wpf
* [Windows and Dialog Boxes](https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/index#windows-and-dialog-boxes)

**Comment by grauwoelfchen** [comment]
Wenn du durchaus Flayouts möchtest, es möglich ist. AmiKo verwendet Mahapps, darum `Flayouts` sieht so aus (Overlay auf Parent Control, wie Left Side Global Menu in jetzige AmiKo App)
 Es wird anders als es auf macOS.

https://mahapps.com/controls/flyouts.html

**Comment by zdavatz** [comment]
1. [Beide](https://github.com/jbe2277/waf/wiki/UWP-vs.-WPF) verwenden XAML. Warum geht es also nicht für unsere WPF App?
2. Prescription View sollte kein Browser-View sein.

**Comment by zdavatz** [comment]
Falls das FlyOut so kompliziert ist, bleiben wir bei Deiner UWP Lösung.

**Comment by grauwoelfchen** [comment]
Dann, versuche ich mal ein bisschen Flyouts von Mahapp auf jetziges Build. Ich denke, dass das wahrscheinlich sich nicht so gut für Prescription View passt an.

Prescription View verwendet _SCHON_ WPF Control, nicht Browser. Siehe [Commits](https://github.com/zdavatz/amiko_csharp/commit/8d86607bd9cd93e2701e6a0f5cead5f93c9fa616#diff-3cb0c44051d1bbad50b802c0dc8e4613R49)

**Comment by zdavatz** [comment]
Ja, das ist besser. Jetzt müssen wir nur noch die Grösse anpassen.

**Comment by zdavatz** [comment]
Ok. Bitte auch die Buttons richtig anschreiben, gleiche wie bei macOS. Nicht vergessen, dass die FR Buttons auch korrekt angeschrieben werden müssen.
