### ISSUE TITLE
Saved/Issued Prescription List (Right Side Area in Main Window)

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#32]
Create `ContentControl` with styl trigger using content template based on `ViewType`'s Mode for Prescription like `MainArea`.

* `WebBrowser` uses SectionTitles `ListBox`
* Form (Prescriptions) uses `ListBox` for file names `TextBlock` for saved prescriptions

**Comment by zdavatz** [comment]
Warum können wir hier nicht XAML verwenden?

**Comment by grauwoelfchen** [comment]
Doch. Es ist XAML.Ich habe über Controls auf XAML format geschrieben. Aber es braucht einfach `Template` property mit `Trigger` im Markup.

**Comment by zdavatz** [comment]
Ok, sehr gut. Danke für die Erklärung.
