### ISSUE TITLE
Add highlight style for active query button

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#34]
Add/set highlighted style for currently selected query buttons (`Präparat` usw.), that user can know which one is active. 

To keep bold border style after active control has been changed (e.g. Click on Search Field) would be enough.

**Comment by grauwoelfchen** [comment]
This bold border will be gone, if active control on the window has been changed.

![query-button-style-for-search-ponstan-praeparat-20180522 png](https://user-images.githubusercontent.com/163063/40330548-4337a0ec-5d88-11e8-80f2-e33c3b5b12cd.png)

**Comment by zdavatz** [comment]
Ja, zur Zeit muss ich immer zwei Mal klicken um eine Art der Suche zu aktivieren. Das finde ich ein bisschen komisch. Ich muss zum Beispiel zwei Mal auf "Präparat" klicken oder zwei Mail auf "Volltext" um den Suchfokus zu setzen.

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Deine Situation ist wahrscheinlich einen anderen Bug für State von Search Queries. Also habe ich neues Issue #39 gemacht.

**Comment by grauwoelfchen** [comment]
This issue should not be closed yet. (not done, yet)
