### ISSUE TITLE
F12 und F1 im VS

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#36]
Funktionieren F12 und F1 bei Dir?

Für Source Doku musst Du im VS F12 drücken. Für Online Doku musst Du im VS F1 drücken.

**Comment by zdavatz** [comment]
[F1](https://stackoverflow.com/questions/13942657/visual-studio-intercepting-f1-help-command) muss funktionieren bei Dir im VS. Ebenso F12.

**Comment by zdavatz** [comment]
Beispiel von F12. Klappt das bei Dir im Vim? Falls ja, bitte einen Screenshot hochladen. ![f12](https://user-images.githubusercontent.com/4953/40439971-db0dd1b8-5ebc-11e8-86f4-22a7c2ad70b5.png)

Beispiel von F1. Klappt das bei Dir im Vim? Falls ja, bitte Screenshot hochladen.
![f1](https://user-images.githubusercontent.com/4953/40440042-19a55ffe-5ebd-11e8-84db-7edd128359f6.png)

**Comment by zdavatz** [comment]
Die Dokumentation zu CSharp und mit F12 und F1 ist wirklich sehr gut. Microsoft hat den Zugang zum Source mit der F12 Taste wirklich vereinfacht. Verwendest Du das auch mit Vim?

**Comment by zdavatz** [comment]
Noch ein Beispiel, nachdem ich F12 gedrückt habe: 

![f12_2](https://user-images.githubusercontent.com/4953/40441158-78b7dadc-5ec0-11e8-93ee-29173acb5678.png)

**Comment by grauwoelfchen** [comment]
Ja, es ist möglich. Ich kann mit Such Funktion (z.B. `K` auf ein Wort usw.) von Vim die Dokumentationen da einfach anschauen. Und auch auf Online kann ich es in meinem Gentoo mit angenehmer Methode lesen, weil ich immer den Kode auf da schreibe. Es ist schon genug, und kein Problem für mich.

Danke für die Tips.
