### ISSUE TITLE
Fix wrong context selected after search query has been changed

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#37]
1. Select `Interaktionen` or `Favoriten` (Context) on Tab Item
2. Click `Volltext` (Search Query Button)
3. Click another Search Query Button

And then,

* `Interaktionen` or `Favoriten` Tab will be unchecked (lost the context)
* Highlighted Tab will be `Kompendium` (back to default)

**Comment by zdavatz** [comment]
Achtung, das ist kein Bug. Es gibt nur eine Volltext-Suche, nämlich die von der Kompendiums-Suche. Die Verbesserung wäre, wenn man auf `Volltext` klickt, dass dann der Fokus auf Kompendium wechselt bei den Reitern oben.

**Comment by grauwoelfchen** [comment]
OK. `Volltext` Such sieht vermutlich spezielle Mode für Such. Es ist möglich nur für `Kompendium` und `Favoriten`.

**Comment by zdavatz** [comment]
Achtung: Wenn Du im `Favoriten` Tab bist, gibt es *Sterne/Favoriten* für `Volltext` und für die normale `Präparat` Suche, je nachdem welche Suche Du gewählt hast. 

Der User kann also eine normale `Präparat` Suche favorisieren (Stern setzen) oder er kann auch eine `Volltext` Suche favorisieren (Stern setzen).

Es werden also andere Sterne gezeigt, je nach dem ob Du `Volltext` oder `Präparat` anklickst bei den Favoriten.

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Ich möchte meine Verständnis mich noch vergewissern, weil Status von jetziges UI Controls (Buttons, Tab, Such Resultat, und Browser)  momentan noch ein bissschen schwer verständlich für mich sind. (Ich habe macOS Version auch angeschaut).

Also, In `Favoriten` Tab, eigentlich, man soll nur Lieblings (favorite) Medikamente in Such Resultat schauen für jede Query Buttons. Oder?

Im Kompendium kann der User jede Medikamente favorisieren.
Im Faroviten kann er noch mehr weiter aus Faroviten auswählen (Nur Auswahl von Farovites und Unfavorisieren sind möglich)

Is das korrekt?

**Comment by zdavatz** [comment]
Der User kann auch eine `Volltext` Suche favorisieren. Diese Favoriten sind dann unter `Favoriten` > `Volltext`.

z.B. nach "Kind" suchen im `Volltext` Modus. Dann ein "Stern" setzen neben "Kind". Dann umschalten auf `Favoriten` und dann auf `Volltext` klicken. Dann siehst Du die `Volltext` Favoriten.

Das sind andere Favoriten als die `Präparate` Favoriten.

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Meinst du, dass es möglich nur Im Tab ausser `Faroviten` ist?

> Der User kann auch eine Volltext Suche favorisieren. Diese Favoriten sind dann unter Favoriten > Volltext.

Das Verhalten im `Faroviten` Tab und `Volltext` Query Button ist beides jeweils anders als andere Tabs und Buttons.

Vor der Suche:
Im Faroviten Tab werden nur Lieblings Medikamente für jeder Queries angezeigt.
In jedem Tab (ausser des Favoriten Tab)  werden leer Resultat für Volltext Query angezeigt.

**Comment by zdavatz** [comment]
Es kommt darauf an, welche Suche Du im `Favoriten` Tab angewählt hast.

In den `Favoriten` kann man auch suchen. Man kann die Favoriten durchsuchen, also die mit einem _Stern_ gekennzeichnete Volltext-Suche oder das Präparat.
