### ISSUE TITLE
Search query button needs click twice to activate

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#39]
See: 
https://github.com/zdavatz/amiko_csharp/issues/34#issuecomment-390880504

**Comment by zdavatz** [comment]
Ich weiss nicht ob das ein Bug ist oder nicht. Ev. funktioniert C# einfach so.

**Comment by grauwoelfchen** [comment]
Es sieht etwas Problem von UI Status Management und Transition wie Tabs (Kompendium usw.) und Query Buttons (Präparat usw.) aus.

**Comment by zdavatz** [comment]
Ja, es wäre besser wenn man nicht zwei Mal klicken müsste. ;) Einmal klicken sollte eigentlich genügen.

**Comment by grauwoelfchen** [comment]
@zdavatz Kannstu du [fix-ui-query-states](https://github.com/zdavatz/amiko_csharp/tree/fix-ui-query-states) mal testen? Es hat noch ein bisschen komische Punkte für UI Status von Volltext Query im Farovites, aber es funkzioniert meistens erwartungsgemäss, denke ich.

Wenn es gut ist, dann ich kann #31 (Such Resultat für Rezepte) machen.

**Comment by zdavatz** [comment]
Etwas mit dem State bei den Favoriten der Volltext-Suche ist noch nicht gut. Schau Dir mal dieses [Video](https://ywesee.slack.com/files/U27FC8WLA/FAWJWLN95/2018-05-24_15-37-47.mp4) an.

**Comment by grauwoelfchen** [comment]
![highlighted-improved-query-toggle-buttons-with-autofocus-textbox-20180525](https://user-images.githubusercontent.com/163063/40523680-cddedd4c-6011-11e8-8353-6235e9d51254.png)

**Comment by zdavatz** [comment]
Ja, das sieht besser aus, als der schwarze Ramen.
