### ISSUE TITLE
Starting the Developer Command Prompt

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#4]
https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs

**Comment by zdavatz** [comment]
And creating a Key: https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-create-a-public-private-key-pair

**Comment by zdavatz** [comment]
I am trying this with Windows PowerShell: https://docs.microsoft.com/de-de/windows/uwp/packaging/create-certificate-package-signing

**Comment by zdavatz** [comment]
CoMed needs a separate signature:
![comed_sig](https://user-images.githubusercontent.com/4953/38933040-2d219d88-4318-11e8-83bd-952f50bd525f.PNG)

1. Debuggen
2. Eigenschaften von CoMed

**Comment by zdavatz** [comment]
Schritte um PFX Datei zu erstellen:
1. `New-SelfSignedCertificate -Type Custom -Subject "CN=ywesee GmbH, C=CH" -KeyUsage DigitalSignature -FriendlyName "Zeno R.R. Davatz" -CertStoreLocation "C:\Users\zdavatz\"`
2. `$pwd = ConvertTo-SecureString -String <Your Password> -Force -AsPlainText`
3. `Export-PfxCertificate -cert "Cert:\LocalMachine\My\<Certificate Thumbprint>" -FilePath <FilePath>.pfx -Password $pwd`
4. Dann hat man eine .pfx Datei.
5. Siehe: https://docs.microsoft.com/de-de/windows/uwp/packaging/create-certificate-package-signing

**Comment by grauwoelfchen** [comment]
@zdavatz Also, dann, wir machen wie so (weil wir gleiche Publisher ID verwenden müssen):

```powershell
> New-SelfSignedCertificate -Type Custom -Subject "CN=3F71A827-F362-4FF2-A406-EA63C19EA85B" -KeyUsage DigitalSignature -FriendlyName "ywesee GmbH" -CertStoreLocation "C:\Users\<User>\"
> $pwd = ConvertTo-SecureString -String <Password> -Force -AsPlainText
> Export-PfxCertificate -cert "Cert:\LocalMachine\My\<Thumbprint>" -FilePath ywesee.pfx -Password $pwd
```

Und,

```powershell
& 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x64\signtool.exe' sign /fd SHA256 /a /f .\path\to\ywesee.pfx -p <Password> .\path\to\appx
```

**Comment by zdavatz** [comment]
sehr gut.

**Comment by zdavatz** [comment]
```
& 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x64\signtool.exe' sign /fd SHA256 /a /f .\AmiKoWindo
ws\ywesee.pfx -p password C:\Users\zdavatz\Documents\VisualStudio\amiko_csharp\AmiKoWindows\bin\Release\Output\yweseeGmbH.CoMedDesitin\yweseeGmbH.CoMedDesitin.appx
Done Adding Additional Store
```
