### ISSUE TITLE
Schriftgrösse der Buttons darf nicht zu klein sein.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#41]
Die Schriftgrösse der _neuen_ Buttons ist zu klein.
![schriftgrosse_zu_klein](https://user-images.githubusercontent.com/4953/40472663-66a4d276-5f3a-11e8-81ab-e3a08d2ddc7a.png)

**Comment by grauwoelfchen** [comment]
In `master` Branch, The texts on those buttons have now exactly same font size as Query Buttons. Let's have a phase for UI parts/controls and Style improvements, later. I'll continue working on tasks for functionalities, right now.

**Comment by zdavatz** [comment]
Ok.
