### ISSUE TITLE
Skript-Error beim Anwählen der Volltext-Suche

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#42]
Es gibt jetzt auch einen Script-Error beim auswählen eines [Volltext-Suchresultats](https://ywesee.slack.com/files/U27FC8WLA/FAWJWLN95/2018-05-24_15-37-47.mp4).

Mit dem VLC Player aus dem Windows-Store, kannst Du die Videos anschauen, oder mit Firefox auf Windows kannst Du die Videos im Browser anschauen.

**Comment by zdavatz** [comment]
Auch dieser [Video](https://ywesee.slack.com/files/U27FC8WLA/FAWJWLN95/2018-05-24_15-37-47.mp4) zeigt, dass etwas komisch ist mit den Favoriten (Präparate und Volltext).

**Comment by grauwoelfchen** [comment]
OK. Ich schaue es nachher an.

Wie ich gestern gesagt habe, fix-ui-query-states` Branch hat einige Verbesserungen und aber noch einige komische Puntke für States von diese Query Buttons und Tab Navigation. Ich gehe zuerst andere neues Funktionen vor.

Aber, Du mischst verschiedene 3 Punkte, und schreibst sie hier auf einmal. Also, Denken wir `Skript Error` Problem auf das Issue. (Ich mache andere Tasks über verschiedene Probleme von Verhalten wie so in deine Screencasts. Sie helfen mir. Danke)

* Wie hast du dieses `Skript Error` (Runtime Error) genommen? (Ich kann nicht das Error auf deinem Screencasts sehen)
* Bist du in `master` Branch? oder jetziges `fix-ui-query-states` Branch?

**Comment by grauwoelfchen** [comment]
Das steht mit #39 und #37 in Zusammenhang.

**Comment by grauwoelfchen** [comment]
So, Ich habe jetzt einige Commits für #39, #34 und #37 zu `fix-ui-query-states` auf Branch Push gemacht. Und Auch `master` hat jetzt schon diese neues Commits für bündige weitere Besprechung (Ich habe jetzt Merge gemacht).

Also einfach bitte testen dieses `Skript Error` Problem auf `master` Branch.

**Comment by zdavatz** [comment]
![script_error](https://user-images.githubusercontent.com/4953/40528715-2b01ff60-5ff2-11e8-9d7c-088f0758556a.png)

Der Skript-Error ist immer noch da. Hast Du überhaupt selber getestet?

**Comment by zdavatz** [comment]
1. Applikation öffnen
2. Zum `Favoriten` Reiter gehen.
3. `Volltext` klicken.
4. Es dauert sehr lange bis die Favoriten für den Volltext laden. Es dauert bedeutend länger als die Favoriten der Präparate zu laden. Die Favoriten der Präparate laden viel schneller. Wieso?

**Comment by zdavatz** [comment]
Zudem: Die Favoriten-Volltext-Suche ist nicht konsistent und sie ist zu langsam.

**Comment by zdavatz** [comment]
Umschalten zwischen den Volltext-Favoriten klappt gar nicht. Umschalten zwischen den Präparate-Favoriten klappt sehr gut. Siehe dieses [Video](https://ywesee.slack.com/files/U27FC8WLA/FAVH29N3T/2018-05-25_08-28-45.mp4)

**Comment by zdavatz** [comment]
Dieser Skript-Error bei der Voll-Text-Suche kommt immer noch.

![volltext_suchresultat](https://user-images.githubusercontent.com/4953/40859812-51193ce4-65e3-11e8-84ee-9089ba7d401c.png)
