### ISSUE TITLE
Set initial highlighted style to Query Button (Präparat Button)

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#44]
Initially, `Präparat` (Title) Query Button is selected (active), but it does not have any highlighte style.

**Comment by zdavatz** [comment]
Screenshot bitte.

**Comment by grauwoelfchen** [comment]
done.

@zdavatz Bitte schaust du an, dass `Präparat` Button Gray (selected) ist. Ich denke, dass das verstandlich für Benutzer ist.
