### ISSUE TITLE
RestAPI von Outlook.com in AmiKo integrieren.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#47]
Wir müssen von der Windows 10 Peoples App Personen importieren können. Das ist ein Weg mit [My People sharing](https://docs.microsoft.com/en-us/windows/uwp/contacts-and-calendar/my-people-sharing#declaring-support-for-the-share-contract)

**Comment by zdavatz** [comment]
Falls es mit der Kontakte App von Microsoft zu kompliziert ist, verwenden wir das [Outlook.com API](https://msdn.microsoft.com/en-us/office/office365/api/mail-rest-operations)

**Comment by zdavatz** [comment]
Hier noch der [Kontakte-Picker](https://github.com/Microsoft/Windows-universal-samples/tree/6370138b150ca8a34ff86de376ab6408c5587f5d/Samples/ContactPicker).

**Comment by zdavatz** [comment]
Diese App machte eine [Kontakte Migration](https://www.microsoft.com/en-us/store/p/contacts-migration/9nblggh40m5x) von Google auf Outlook.com. Somit sollten wir auf das Outlook.com Adressbuch auch zugreifen können.

**Comment by zdavatz** [comment]
Hier beginnt es mit dem [REST API](https://docs.microsoft.com/en-us/outlook/rest/get-started) von Outlook.

**Comment by zdavatz** [comment]
Aha. Das ist gut. Hier hast Du auch ein [WPF Beispiel](https://github.com/SharePoint/PnP/tree/master/Samples/Office365Api.Overview).

**Comment by grauwoelfchen** [comment]
@zdavatz Es sieht jar technisch möglich als alternative Methode (gegen Integration mit People App via `ContactPicker`.) aus. Wir können gerade noch nicht einfach Desktop Bridge für `ContactPicker` verwenden, weil es UWP Componet ist.

Ach ich habe einmal gefacht, dass die Verwendung von Contacts auf Office 365 oder Outlook Online möglich ist. Aber ist das gut und normal für __Patienten__ Information auf Online Storage (für eine Ärzte) zu hochladen?

**Comment by zdavatz** [comment]
Ja, ich denke das macht Sinn, dass man die Adressen wie Outlook.com reinladen kann. Am Anfang ist das AmiKo-Adressbuch des Arztes leer.

**Comment by zdavatz** [comment]
Die Idee ist aufgekommen ein Nuget zu erstellen um via Outlook.com Adressen abzuholen. Es gibt schon mehrere Projekte von Microsoft, siehe: [NetOffice](https://www.nuget.org/packages/NetOffice.Outlook/) und viele andere [Pakete](https://www.nuget.org/packages?q=outlook+api)

**Comment by zdavatz** [comment]
Es gibt auch schon ein [Nuget](https://www.nuget.org/packages/Microsoft.Office365.OutlookServices-V2.0/) von Outlook.com.

**Comment by zdavatz** [comment]
Das ist der [Guide](https://apps.dev.microsoft.com/portal/guided-setup/introduction?appType=mobileAndDesktopApp&appTech=windowsDesktop&appId=f98ad3e7-3120-45f6-ad82-060734f56ad5)

**Comment by zdavatz** [comment]
REST API of Outlook 2.0 vs Graph API, some [differences](https://stackoverflow.com/questions/34480656/outlook-rest-api-vs-microsoft-graph).

**Comment by zdavatz** [comment]
siehe #50
