### ISSUE TITLE
Kontakte via CSV importieren

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#50]
Outlook can auch zu [CSV](https://support.office.com/en-us/article/export-contacts-from-outlook-10f09abd-643c-4495-bb80-543714eca73f#ID0EAABAAA=Office_365) exportieren.

**Comment by zdavatz** [comment]
Man muss

1. das CSV laden können.
2. im geladenen CSV suchen können.
3. aus dem geladenen CSV _alle_ Kontakte importieren können.
4. aus dem geladenen CSV _nur einen_ Kontakt importieren können.

**Comment by zdavatz** [comment]
Das ist ein Export vom [Outlook](https://ywesee.slack.com/files/U27FC8WLA/FB11P69RV/outlook_export.csv)

**Comment by zdavatz** [comment]
Bitte auch mit Google-Export testen:
![google-export-kontakte](https://user-images.githubusercontent.com/4953/42439655-c2b97b82-8363-11e8-95c9-f72f75664a46.jpg)

**Comment by zdavatz** [comment]
Das ist der Import vom Google (Outlook-Export).
![google-export-gmail-kontakte](https://user-images.githubusercontent.com/4953/42439846-49bfd90a-8364-11e8-81dc-9ce6f13f46b6.jpg)

**Comment by zdavatz** [comment]
![csv-import](https://user-images.githubusercontent.com/4953/42440441-0d87c14e-8366-11e8-9440-19e9307ac29b.png)

**Comment by zdavatz** [comment]
Ich habe versucht diese Datei zu importieren: https://ywesee.slack.com/files/U27FC8WLA/FBLPC0U4U/kontakte.csv

aber ich kriege diesen Crash:

![kontakte_outlook com-import-crash](https://user-images.githubusercontent.com/4953/42444773-330ed30c-8371-11e8-8cf2-f675c5874768.png)

mit dem Commit: 78aa62ccbb443c5a73aa958ac815b4f2

**Comment by zdavatz** [comment]
CSV Import klappt gut via dem Export von Outlook.com. Es werden nicht alle Adressen importiert, aber man kann die Adressen auswählen, welche man importieren möchte. Das ist sehr gut.

**Comment by zdavatz** [comment]
Wenn die CSV-Datei mehr als 2'000 Einträge hat, dann wird AmiKo ein bisschen langsam oder kann auch abstürzen. Ich habe mit meinem Outlook-Export von contacts.google.com probiert. Alle Kontakte werden richtig geladen aber _Suchen_ laggt ein bisschen.

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Ich schaue noch ein bisschen CSV Import an, ob wir noch besser Performance machen können.

**Comment by grauwoelfchen** [comment]
@zdavatz Bitte versuchst du es mal wieder. Ich habe einige Commits für Improvements gemacht. Es korrespondiert auch CSV von Google.com. Den Import funkzioniert ein bisschen langsam, weil wir müssen einige verschieden Felden untersuchen. Aber es absturzt nicht mehr und Such geht schneller, weil es unrechte Zeilen entfernt zum Import.

**Comment by zdavatz** [comment]
Ok, das werde ich testen. 

Frage: Könnte man auch eine "Import all" Funktion machen wo alle Einträge importiert werden bei denen die Pflichtfelder vollständig sind?
