### ISSUE TITLE
PatientDB is missing on Create

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#52]
Wenn ich `bin` und `obj` Dir lösche, dann kriege ich diesen Error: 
![bin_obj_geloescht](https://user-images.githubusercontent.com/4953/40859519-5cd80764-65e2-11e8-8e8c-fd4b539ec118.png)

**Comment by zdavatz** [comment]
Wenn ich dann die App neu starte, dann klappt es wieder.

**Comment by grauwoelfchen** [comment]
@zdavatz Vielleicht du sie löscht, während die letze App noch läuft. nicht wahr? Oder, Windows hat manchmal noch komische Process für eine Weile auch bei Mir da nach die App Schliessen. Es kann vielleicht das Problem machen. Dieses `patients` Table wird am Boot der App generiert. Auch ich versuche es mal.

**Comment by zdavatz** [comment]
ok. Ich versuche es auch nochmals.

**Comment by grauwoelfchen** [comment]
OK. I have just reproduced this error. It seems that that database table is certainly created, but it's not finished yet on the initial loading of contact entries.

**Comment by zdavatz** [comment]
gut.
