### ISSUE TITLE
"Öffnen" Button bitte entfernen

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#53]
AmiKo für macOS hat keinen Öffnen Button. Diesen bitte löschen.

![oeffnen_button_loeschen](https://user-images.githubusercontent.com/4953/40859662-df04e50e-65e2-11e8-95a6-71466445b134.png)

**Comment by grauwoelfchen** [comment]
@zdavatz Ich habe eigentlich gedacht, dass wir später den Workflow von User über ein Kontact Data Loading für neues Rezept besprechen. Aber es ist egal. Dann Ich lösche `Öffnen` Button, und mache ich nur `Double Click` Event wie jetziges macOS Version.

**Comment by zdavatz** [comment]
genau! Und CSV Import kommt über das Icon unten rechts.
