### ISSUE TITLE
BirthDate Field Placeholder and Input Validation in Addressbook

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#54]
* Set placeholder `DD.MM.JJJJ` (DE) for`Geburtstag`
* Create input validation

**Comment by zdavatz** [comment]
Bitte das auch noch machen. Das Feld muss validiert werden.
![gebr_feld_validation](https://user-images.githubusercontent.com/4953/41022299-5fbc90dc-6969-11e8-9935-18f83bf9e6f2.png)

**Comment by grauwoelfchen** [comment]
Unit tests for the Input (Date format) Validation:
(NG)
https://github.com/zdavatz/amiko_csharp/blob/73198832385ae43ec34b133f5ff425e11458fb4c/AmiKoWindows.Tests/src/PatientDbTest.cs#L25-L28
(OK)
https://github.com/zdavatz/amiko_csharp/blob/73198832385ae43ec34b133f5ff425e11458fb4c/AmiKoWindows.Tests/src/PatientDbTest.cs#L35-L36


Placeholders:
* `DD.MM.JJJJ` (de)
* `DD.MM.AAAA` (fr)
