### ISSUE TITLE
Appx Package (AmiKo and CoMed)

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#60]
Add packaging support for release build using bare `MakeAppx.exe`.

https://docs.microsoft.com/en-us/windows/uwp/packaging/create-app-package-with-makeappx-tool

**Comment by zdavatz** [comment]
Im Windows 10 Store muss man die folgenden Dateien hochladen:
```
.appx, .appxbundle, .appxupload, .xap
``` 
![appx](https://user-images.githubusercontent.com/4953/42456450-438e6dae-8395-11e8-9cba-f4a22c1cad7f.png)
Das erstellen der Datei sollte ohne Probleme gehen aus dem VisualStudio heraus oder via CommandLine.

Siehe auch: https://github.com/zdavatz/amiko_csharp/issues/5

Die App muss auch validiert werden mit dem [Windows App Certification Kit](https://developer.microsoft.com/en-us/windows/develop/app-certification-kit)

**Comment by grauwoelfchen** [comment]
I'll try Desktop App Converter.

https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter#no-installer-conversion
