### ISSUE TITLE
Kein Abstand zwischen den Hintergrundfarben der angewählten Person

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#63]
Kein Abstand zwischen den Hintergrundfarben der angewählten Person und dem Mouse-Over. Zwichen den Beiden Einträgen sollte es kein _weiss_ haben. Rechts und links schon, aber nicht dazwischen.

![kein-abstand-zwischen-balken](https://user-images.githubusercontent.com/4953/40914331-148eed98-67f8-11e8-9646-e30de83dd9a6.png)

**Comment by grauwoelfchen** [comment]
Eine Items auf die Liste haben gerade einfach gleich Style wie Such Resultat von Patinfo (`Präparat` usw.). Also Ich mache neues Style für die Items und die Kontakt Liste.

**Comment by zdavatz** [comment]
oder wir lassen es mal so.

**Comment by grauwoelfchen** [comment]
@zdavatz Auf jeden Fall, wir müssen den Rand ausser Text der Name in die Liste Clickable machen. Ich aktualisiere auch das Style. Ich sage Dir es wieder.

**Comment by grauwoelfchen** [comment]
@zdavatz Es hat noch 1px `Padding` in ListBox. Ich habe versucht, es zu entfernen, aber es sieht schwierig aus. Weil es die Bestimmung von Style ignoriert. Ich schaue es mal wieder noch ein bisschen zum Schluss, wenn wir genug Zeit haben.

Aber, man kann auch den Rand Klick machen.

![reduced-margins-for-listbox-item-20180607](https://user-images.githubusercontent.com/163063/41077441-8a22dfc8-6a51-11e8-8688-f0e538e8f949.png)

**Comment by grauwoelfchen** [comment]
And, Updated also `-` (Minus) and `+` (Plus) Bottns, to have extra padding as clickable and background color on mouse hover.

![minus-button-mouse-hover-style-and-padding-20180607](https://user-images.githubusercontent.com/163063/41079606-69f48bc8-6a5d-11e8-9984-9ae5785914f9.png)

**Comment by grauwoelfchen** [comment]
This issue will be closed if above commits [4e02a1a](https://github.com/grauwoelfchen/amiko_csharp/commit/4e02a1aca29bcc130ee1486b892cffec9cf3d60b) and [943093d](https://github.com/zdavatz/amiko_csharp/commit/943093d0711081e04dd4e997feda782788c249cf) are merged.
