### ISSUE TITLE
Delete issued prescriptions

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#69]
Related to #64

**Comment by zdavatz** [comment]
Warum kreierst Du noch einen Issue wenn ich schon einen gemacht habe? Das verstehe ich nicht.

**Comment by grauwoelfchen** [comment]
@zdavatz Nein. Ich ignoriere nicht auch sie, und Ich habe auch #64 geschaut. Aber Ich möchte den Löschen nur für Rezept auf dieses Issue machen.
