### ISSUE TITLE
Add in-app address book

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#7]
In this step, address book does not have yet any features for imporitng, editing or search. Just add simple data store with views (floating window).

**Comment by zdavatz** [comment]
1. User muss in den Adressen der Peoples App suchen können.
2. User muss aus der Peoples App eine Adresse übernehmen können.
3. Adresse muss im AmiKo (sqlite) Adressbuch gespeichert werden.

**Comment by zdavatz** [comment]
Zu diesem Screenshot:

1. Alle Felder müssen entweder DE oder EN sein. Aber nicht beides. Buttons sind zur Zeit DE. Wenn das OS die Sprache nicht steuert, bitte alle Felder auf DE anschreiben und kein EN verwenden.
2. Geschlecht ist abgekürzt mit "m" oder "f". Siehe macOS.
3. Wozu ist der Stern?
4. Wozu dient das "Dreieck"?
5. Die Schrift von "Address Book" ist zu klein. Sie muss gleich gross sein wie alle anderen Schriften auch.
6. Adress Book -> Adressbuch. Alles auf DE bitte. Auch die Buttons und Texte.
7. "Sex" ist nicht schön aligniert.
8. Im Geburtstagsfeld muss "dd.mm.yyyy" stehen, sodass der User weiss welches Format er verwenden muss.

**Comment by zdavatz** [comment]
Anstelle vom Dreieck links unten in der Ecke, bitte dieses Icon verwenden:

![outlook-icon-61615](https://user-images.githubusercontent.com/4953/40645983-3cf35f50-6328-11e8-9979-383a08368bbd.png)

**Comment by grauwoelfchen** [comment]
@zdavatz Was ist Licenz für das Icon? (Und woher hast du das genommen?)

**Comment by grauwoelfchen** [comment]
@zdavatz Dann besprechen wir das auf Issues #48 (As an Issue auf `UI Improvements` project)

**Comment by zdavatz** [comment]
Ok.
