### ISSUE TITLE
Klick auf den Löschen Button ist noch ein bisschen komisch.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#71]
Wenn ich auf den Löschen Button klicke, dann reagiert er nicht immer. Siehe [Video](https://ywesee.slack.com/files/U27FC8WLA/FB2BHSXK5/2018-06-06_09-05-45.mp4)

**Comment by grauwoelfchen** [comment]
@zdavatz Ich denke, dass der Grund des Problem auch Clickable Area ist (wie #63). Ich schaue es mal.
