### ISSUE TITLE
Doppelte Adresse, Hash-Funktion schon implementiert?

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#72]
Kontrollierst Du schon den Hash der Adresse wie auf macOS?

Zur Zeit kann ich die gleiche Adresse zweimal abspeichern. Vorname, Nachname und Gebr.-Datum sind dieselben.

![hash_check_for_duplicate_address](https://user-images.githubusercontent.com/4953/41032731-92b426b0-6984-11e8-91e7-9767b61d7d35.png)

Gleiche Adressen sollte man nicht doppelt abspeichern können.

**Comment by zdavatz** [comment]
![zeno_2](https://user-images.githubusercontent.com/4953/41032786-c27930b6-6984-11e8-9872-2395fbf803cd.png)

Gleicher Vor- und Nachname, gleiches Gebr.-Datum.

**Comment by grauwoelfchen** [comment]
@zdavatz Ja. Die App hat schon fast gleich Hash Value wie macOS Version. Aber es verwendet noch nicht über das Check wie so etwas.

Ist das Verhalten in Erwartung? dann mache ich so.
Aber Unique Constraints in DB passt normalerweise für den Zweck an. Und Hash wird auch Kollision in Zukunft haben.

**Comment by zdavatz** [comment]
Ich schliesse das Ticket. Ich werde es testen sobald wir die Rezepte importieren. Auf macOS kann man auch zwei Personen mit dem gleichen Namen, Vornamen und Gebr.-Datum haben.
