### ISSUE TITLE
Adresse wird nur angewählt wenn man auf den Namen klickt

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#73]
[Adresse wird nur angewählt wenn man auf den Namen klickt](https://ywesee.slack.com/files/U27FC8WLA/FB1SG2TRN/2018-06-06_12-27-57.mp4). Der grauen Balken gibt keinen Feedback und die Adresse wird nicht angewählt.

**Comment by grauwoelfchen** [comment]
@zdavatz Ja. Ich mache das auf #63.

**Comment by zdavatz** [comment]
Ok. Dann schliesse ich das Ticket.
