### ISSUE TITLE
Display entries count in AddressBook

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#78]
Im AmiKo Adressbuch werden die Adressen nicht korrekt gezählt. Es heisst immer noch "0", dabei sind zwei Adressen vorhanden. Siehe unten rechts, 
![wrong_count](https://user-images.githubusercontent.com/4953/41141319-e6b4cb8e-6af1-11e8-8442-123c7a22401f.png)

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Ich mache es einfach noch nicht. Ich mache es nachdem Such Funktion #10
