### ISSUE TITLE
Add new/edit functionality to in-app address book

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#8]
Add new/edit functionality to in-app address book.

Related with #7

**Comment by zdavatz** [comment]
Die Schrift vom roten Satz ist zu klein. Die Schrift darf nicht kleiner sein als die Schrift der Buttons.

**Comment by grauwoelfchen** [comment]
![increased-text-size-margins-for-label-and-message-20180601](https://user-images.githubusercontent.com/163063/40851839-83505cf4-6603-11e8-90d4-dcee6aa8e95f.png)

**Comment by grauwoelfchen** [comment]
This issue is themed only for capabilities to new/edit entry on the Form in AddressBook. Although, about the rest of the work for AddressBook, see #57, #58.

**Comment by grauwoelfchen** [comment]
merged to `master` [c31b247f40169278f0cc601caecd26873d76f545](https://github.com/zdavatz/amiko_csharp/commit/c31b247f40169278f0cc601caecd26873d76f545)
