### ISSUE TITLE
Adresseinträge Suchen geht nicht

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#80]
Die Suchfunktion bei den Adresseinträgen geht noch nicht. Die Suche darf nicht Case-Sensitive sein. Man muss nach Vorname oder Nachname suchen können.

**Comment by grauwoelfchen** [comment]
Ich mache es  #10

**Comment by zdavatz** [comment]
Ok.

**Comment by grauwoelfchen** [comment]
@zdavatz Man kann mit Vorname, Nachname, **Wohnort** und **PLZ** aus Patientendatenbank suchen. Und mit Whitespace (wie `zeno d`), auch `AND` Filter machen.

Es ist gleich mit macOS und iOS.

**Comment by zdavatz** [comment]
super! Danke!
