### ISSUE TITLE
Update patient_id Hash implementation

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#81]
Update `patient_id` implementation (To make it cross-platform, cross-language and cross-version on platform/sdk)

Regulation:

* Use `SHA256` for hashed value.
* Make source string lowercase (`Davatz`, `DAVATZ` -> `davatz`).
* Order is `FamilyName`, `GivenName` and `Birthdate` (It's same current implementation in iOS and macOS)
* Birthdate field does not have `0`. (`2.6.1942`)

Source string will be like this: `davatz.zeno.2.6.1942`

```
patient_id looks like:
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

NOTE:

The possibility of hash collision remains based on original product concept for `patient_id` same as `[NSString hash]` usage.

**Comment by zdavatz** [comment]
cool, thanks for documenting.

**Comment by grauwoelfchen** [comment]
Note:
* `Uid` should be generated every time if `GivenName`, `FamilyName` and `GivenName` has been changed.
* For example, If user changes `Birthdate` of the existing contact, new contact entry will be created, because `Uid`  has been changed. (same as `GivenName` and `FamilyName`, but these fields are case in-sensitive)
* The insertion of new contact entry with same `Uid` with existing one, should be fail.

In early Implementation (in macOS and iOS), it seems that `Uid` was created only once at Insertion using `[NSString hash]`. If user updates `Birthdate` or `GivenName` etc. `Uid` had never been changed. In this case,  Prescription Import on cross-apps didnt' work. Thus, we need to update also `Uid` if user updates `FamilyName`, `GivenName` or `Birthdate`. And, in background, It needs also changes of bunch of issued prescriptions (`patient_id` field in JSON) and user directory (because directory named with `Uid`) in app.

**Comment by zdavatz** [comment]
https://github.com/zdavatz/amiko_linux/issues/26

**Comment by grauwoelfchen** [comment]
I've just updated the examples in the description (added comments and a command example) to avoid the confusion on https://github.com/zdavatz/amiko_linux/issues/26#issuecomment-683806759.

**Comment by bettar** [comment]
When you say "Birthdate field does not have 0" I assume you mean "Birthdate field does not have **leading** 0", otherwise 20.6.1942 would become 2.6.1942
