### ISSUE TITLE
Falls keine Arztadresse vorhanden ist Button zeigen

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#85]
Falls keine Arztadresse vorhanden ist, bitte den Button zeigen
`Bitte Arztadresse hinzufügen`
Wenn man Button anklickt, dann gehen die leeren Felder auf.
Auf Französisch heisst der Button
`Ajoutez l'addresse du Médecin s.v.p.`

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Aber, meinst du `Message` unten der Felden oder `Text` auf Button? (Und welche Button?, `Neues Rezept` Button oder?)

Ich denke, dass `Message` und Disabled Button ist einfacher zu machen.

**Comment by zdavatz** [comment]
Keine leeren Platzhalter anzeigen. Einfach einen Button anzeigen, wenn noch keine Arztadresse vorhanden ist.

![bitte_arztadresse_hinzufugen](https://user-images.githubusercontent.com/4953/41288726-a03e2dc2-6e47-11e8-9429-10a18672d35a.png)

**Comment by zdavatz** [comment]
So wäre dann der Button:

![button](https://user-images.githubusercontent.com/4953/41288819-ee987284-6e47-11e8-8bc2-b01ad236c110.png)

**Comment by zdavatz** [comment]
Der Button ist nur vorhanden, wenn keine Arzt-Adresse da ist.

**Comment by zdavatz** [comment]
Wenn die Arztadresse einmal eingegeben ist, ist die Frage wo man sie wieder ändern kann.
a) entweder im Einstellungen Menu.
b) Die Arztadresse wir auch im Patientenadressbuch gespeichert, mit einem speziellen Flag.

Ev. ist b) einfacher.

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Ich mache zuerst das Button. Möchtest du `roten` Button? oder normal wie `Patient suchen`?

**Arztadresse** wird in ApplicationSettings gespeichirt. Es ist wie gleich `NSUserDefaults` auf macOS. Es ist speziell Data-Store für Application oder User.
https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/application-settings-overview

Jetzt, man kann via Einstellungen Menu das Flyout öffnen. Dann, Ich mache, dass User auch mit das Button (oben) das Flayout öffnen kann.

**Comment by zdavatz** [comment]
Normaler Button wie _Patient Suchen_.

**Comment by zdavatz** [comment]
Wir brauchen keinen Extra-Button für den Fly-Out. Noch besser wäre, wenn die Arzt-Adresse auch bei den Patienten auftauchen würde, einfach mit einer anderen Hintergrund-Farbe, weil es die Arztadresse ist. Aber falls das zu kompliziert ist machen wir einen neuen Menupunkt "Arztadresse" in den Einstellungen.

**Comment by zdavatz** [comment]
Das ist gut. 

![gut](https://user-images.githubusercontent.com/4953/41342031-8901655c-6efb-11e8-8574-2aaf2ee83166.png)

Jetzt fehlt nur noch der Button.

https://user-images.githubusercontent.com/4953/41288819-ee987284-6e47-11e8-8bc2-b01ad236c110.png

**Comment by grauwoelfchen** [comment]
@zdavatz 

> Normaler Button wie Patient Suchen.

OK.

> Wir brauchen keinen Extra-Button für den Fly-Out.

Dann mache ich kein Button, sondern einen `Label` für den Text `Bitte Arztadresse hinzufügen`. Und franzözischer Text?

**Comment by grauwoelfchen** [comment]
@zdavatz Was meinst du **Action** von das **Button**?

Ich habe gesagt:
Ich mache, dass User auch mit das Button (oben) das Flayout öffnen kann.

Aber, du sagst:
Wir brauchen keinen Extra-Button für den Fly-Out.

**Comment by zdavatz** [comment]
Wir brauchen den Button, wie ich gesagt habe.

**Comment by zdavatz** [comment]
Ich denke, Du hat nicht verstanden was ich mit meinem [Kommentar](https://github.com/zdavatz/amiko_csharp/issues/85#issuecomment-396861269) gesagt habe.

Für mich ist das Flyout das linke Menu. Nicht der Button. Den Button brauchen wir, falls keine Arztadresse vorhanden ist. 

![button_vs_flyout](https://user-images.githubusercontent.com/4953/41525112-345edbfe-72e0-11e8-9c34-167699276e24.png)

**Comment by grauwoelfchen** [comment]
@zdavatz Nein. Ich meine, dass Alle **Normal** Button etwas Event (Action wie Click) hat. Wenn du nicht Text Label möchtest, sondern **Button** meinst, es soll etwas das Event haben.

Ich habe das Button als einen Beispiel auf `master` merge gemacht. Bitte versuchsht du es mal.
