### ISSUE TITLE
Required Fields on Doctor Address Form

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#86]
Required:

* GivenName (`Name`)
* FamilyName (`Vorname`)
* Address (`Adresse`)
* City (`Wohnort`)
* Zip (`PLZ`)
* Email (`Email`)
* Picture (`Unterschrift`)

Optional:

* Title (`Titel`)
* Phone (`Telefonnr.`)

**Comment by grauwoelfchen** [comment]
@zdavatz Ist das OK für dich? macOS und iOS hat keine Pflichtfelder. Aber wir brauchen die Felden für #85.

**Comment by zdavatz** [comment]
Unterschrift ist auch ein Pflichtfeld.

**Comment by grauwoelfchen** [comment]
@zdavatz OK. (Description updated)

**Comment by zdavatz** [comment]
Lass mich wissen wann ich testen kann.
