### ISSUE TITLE
Profile loading into the Prescription View

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/amiko_csharp#88]
(Doctor's) saved profile (`Arztadresse`) will be shown in Prescription View.

Related #59

**Comment by zdavatz** [comment]
Falls keine Arztadresse vorhanden ist, dann den Button anzeigen, siehe: https://github.com/zdavatz/amiko_csharp/issues/85

**Comment by zdavatz** [comment]
Wenn ich Doppelklick, dann geschieht gar nichts. Die Patienten-Adresse wird nicht übernommen.
