### ISSUE TITLE
Grösse vom Unterschriften Fenster?

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#90]
Dieses Bild
![zeno_paint_unterschrift](https://user-images.githubusercontent.com/4953/41455591-f2c5da44-707d-11e8-883d-cee9f4dad37d.png)
 wird **zerquetscht**.
![zerquetscht](https://user-images.githubusercontent.com/4953/41455614-0659c6b0-707e-11e8-9c3a-e23380182c12.png)

Diese Unterschrift habe ich mit Paint 2D gemacht. Das geht sehr gut!

**Comment by zdavatz** [comment]
Diese Grössen müssen unterstützt sein:

**Höhe: 383
Breite: 134**

oder

**Breite: 383
Höhe: 134**

**Comment by zdavatz** [comment]
Die Fenstergrösse muss also 383x383 sein.

**Comment by zdavatz** [comment]
![383x383](https://user-images.githubusercontent.com/4953/41455822-c7f6a298-707e-11e8-8ac1-62de1ab6f97f.png)

**Comment by zdavatz** [comment]
In der Rezeptansicht sieht man dann Foto oder Unterschrift.
![foto_oder_unterschrift](https://user-images.githubusercontent.com/4953/41455966-5bb1e4de-707f-11e8-9380-65c400f83844.png)

**Comment by grauwoelfchen** [comment]
@zdavatz OK. Ich mache Resize mit  Aspekt Ratio (width und height) von Original Image. Jetzt Image ist noch einfach fixed size.

**Comment by zdavatz** [comment]
Genau. Dann hat es die gleiche Grösse wie auf AmiKo iOS und Generika-Android App.

**Comment by grauwoelfchen** [comment]
Note:

* Embed original (size) Image into Prescription (`.amk` File).
* Display thumbnails resized keeping aspect ratio.

**Comment by zdavatz** [comment]
Hast Du die Grösse vom Fenster angeschrieben?
