### ISSUE TITLE
kein Kamera icon

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#91]
Ich sehe noch kein Kamera icon beim letzten Commit 65c8a9d0aff5100f04

![sehe_kein_kamera_icon](https://user-images.githubusercontent.com/4953/41501922-b9972c42-71ad-11e8-998a-7cda4de86f10.png)

**Comment by grauwoelfchen** [comment]
@zdavatz Bitte machst du pull mal auf  `master`.

**Comment by zdavatz** [comment]
Ich sehe nach wie vor kein Kamera-Icon. Kommt das Camera-Icon nur, wenn man eine Kamera angeschlossen hat?

**Comment by grauwoelfchen** [comment]
@zdavatz Ich denke, dass dein Build nun jetzt ohne das Problem geht. (wie wir kurz vorher zusammen die Prozedur auf Telefon uns vergewissert haben). Bitte sagst du mir, wenn das wieder etwas komisch ist.
