### ISSUE TITLE
wenn keine Unterschrift dann Default Profile-Foto nehmen wenn man auf "Speichern" klickt.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#92]
Wenn es keine Unterschrift gibt und der User auf _Speichern_ klickt, dann muss das Default-Profil-Foto genommen werden.

![wenn_keine_unterschrift_dann_default_unterschrift](https://user-images.githubusercontent.com/4953/41501933-2111ffc8-71ae-11e8-908f-b27190afc33e.png)

**Comment by grauwoelfchen** [comment]
@zdavatz Default Foto kommt jetzt am nur Boot von die App, wenn es kein Profile-Foto gibt. Nachdem Löschen, Wenn immer Default Foto da ist, Ich denke, dass es ist trübselig ist. Möchtest du wirklich das?   Wenn du die App ohne Profile-Foto schliessen, du kannst wieder Default-Foto sehen.
Und, Wir haben schon das Required Validation von das Feld. Darum Benutzer muss bestimmt etwas einen Foto setzen.

**Comment by zdavatz** [comment]
Ich teste nochmals.

**Comment by zdavatz** [comment]
Wenn man das Unterschrift-Bild löscht, gibt es keine Möglichkeit zum Profilfoto zurückzukommen. Es gibt keinen Abbrechen Button. Das ist umständlich. Darum schlage ich vor: Wenn keine Unterschrift vorhanden, dann einfach das Profilfoto nehmen.

**Comment by zdavatz** [comment]
Die Schritte zum reproduzieren sind:
1. Unterschrift wählen.
2. Speichern klicken.
3. Auf "X" klicken um das Unterschrift-Bild zu löschen.
4. Auf _Speichern_ klicken.
5. Dann muss das Default-Foto übernommen und angezeigt werden.
