### ISSUE TITLE
Der Titel des Arztes wird nicht übernommen.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#94]
Der Titel aus der Arztadresse wird nicht übernommen.

![titel_fehlt_2](https://user-images.githubusercontent.com/4953/41533902-bbd74e6a-72fc-11e8-82f1-437c3fd688d9.png)
![titel_fehlt](https://user-images.githubusercontent.com/4953/41533903-bbfe2328-72fc-11e8-9403-b62072cecf5e.png)

**Comment by grauwoelfchen** [comment]
@zdavatz Bitte versuchst du mal `master`.
