### ISSUE TITLE
Gewicht, Grösse, Geschlecht Gebr.-Datum bitte auch anzeigen beim Patienten.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#96]
unterhalb vom Namen wie beim Generika App.

![gewicht_grosse_geschlecht_plz_ort](https://user-images.githubusercontent.com/4953/41584814-91dfa060-73a8-11e8-9ec3-9653ee16f462.png)

**Comment by grauwoelfchen** [comment]
@zdavatz Du kannst Outputs hier (in Tests) sehen:
https://github.com/zdavatz/amiko_csharp/commit/f55c3790a983ebfc1a7423aa665355b052de9fae#diff-44e18ab54d389a02730f2131409121deR125

Weil einige Felden Optional sind, Ich habe wie oben gezeigt.
