### ISSUE TITLE
Arztadresse anzeigen im prescription branch geht noch nicht

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_csharp#99]
Arztadresse anzeigen im _Prescription_ Branch geht noch nicht.

![arztadresse_anzeigen](https://user-images.githubusercontent.com/4953/41701862-5344e310-752e-11e8-95c1-d87f4c953c84.png)

Wenn das wieder geht, bitte das Ticket schliessen.

**Comment by zdavatz** [comment]
Nach einer Weile kommt das:

![nach_einer_weile](https://user-images.githubusercontent.com/4953/41701943-a1a38c1e-752e-11e8-804d-d18f23d3ec68.png)

aber der Button ist immer noch vorhanden.

**Comment by grauwoelfchen** [comment]
@zdavatz Ich habe einen Issues ganz gleich wie das #98. Ich mache es auf da.

**Comment by grauwoelfchen** [comment]
Related #98
